# -*-python-*-

from openalea.sconsx import config, environ
import os
import sys
pj = os.path.join
ALEASolution = config.ALEASolution

options = Variables(['../options.py', 'options.py'], ARGUMENTS)
options.Add(BoolVariable('with_efence', 'build tests with efence library', 0))
options.Add(BoolVariable('DEBUG', 'my debug', 0))

tools = ['boost_python'] #, 'vplants.tool','qt4', 'install', 'alea']

env = ALEASolution(options, tools)
env.AppendUnique(CXXFLAGS=['-x', 'c++', '-std=c++0x'])

# Fix for Conda
env.AppendUnique(CPPPATH=[sys.prefix + '/include'],
                 LIBPATH=[sys.prefix + '/lib'])

# Build stage
prefix = env['build_prefix']
SConscript(pj(prefix,"src/cpp/SConscript"),
           exports='env')
# SConscript(pj(prefix,"src/py/wrapper/SConscript"),
#            exports='env')
# SConscript(pj(prefix,"src/wrapper/SConscript"),
#            exports='env')

Default("build")
