# -*-python-*-

import os
bn = os.path.basename
pj = os.path.join

Import( "env" )

lib_env = env.Clone()
lib_env.Append(CPPDEFINES=['TREEMATCH_MAKEDLL'])

# Export Symbols on Windows
if lib_env['compiler'] == 'mingw':
    LINKFLAGS=["-enable-stdcall-fixup",
               "-enable-auto-import",
               "-enable-runtime-pseudo-reloc",
               "-s"]
    lib_env.AppendUnique(LINKFLAGS=LINKFLAGS)


# Install headers
includes = lib_env.ALEAGlob("*.h")
lib_env.ALEAIncludes("tree_matching2", includes)


#Sources

sources = lib_env.ALEAGlob('*.cpp')
sources += lib_env.ALEAGlob('*.cpp',dir='*')

#print sources
lib_env.Append(LIBS=[])

lib = lib_env.ALEALibrary( "vptree_matching2", sources)
