# -*-python-*-

import os

Import("env")

# Export symbols under windows
if env['compiler'] == 'mingw':
    LINKFLAGS=["-enable-stdcall-fixup",
               "-enable-auto-import",
               "-enable-runtime-pseudo-reloc",
               "-s"]
    env.AppendUnique(LINKFLAGS=LINKFLAGS)


py_dir = '../tree_statistic'

# Build wrappers as shared libraries
#sources = Split("""""")

LIBS = ['vptool', 'vpstat_tool', 'vpsequence','vptree_statistic']
env.AppendUnique(LIBS=LIBS)

env.ALEAWrapper(py_dir+'/trees', "ctree", ["trees/ctree.cpp"])
env.ALEAWrapper(py_dir+'/trees', "ctrees", ["trees/ctrees.cpp"])
env.ALEAWrapper(py_dir+'/int_fl_containers', "int_fl_containers", ["int_fl_containers/int_fl_containers.cpp"])
env.ALEAWrapper(py_dir+'/hmt', "chmt", ["hmt/chmt.cpp"])

