HIDDEN_SEMI-MARKOV_CHAIN

3 STATES

INITIAL_PROBABILITIES
0.4 0.3 0.3 

TRANSITION_PROBABILITIES
0.0 0.5 0.5
0.0 0.0 1.0
0.0 0.0 1.0

STATE 0 OCCUPANCY_DISTRIBUTION
NEGATIVE_BINOMIAL   INF_BOUND : 1   PARAMETER : 1   PROBABILITY : 0.1

STATE 1 OCCUPANCY_DISTRIBUTION
NEGATIVE_BINOMIAL   INF_BOUND : 1   PARAMETER : 1   PROBABILITY : 0.1


2 OUTPUT_PROCESSES

OUTPUT_PROCESS 1 : PARAMETRIC

STATE 0 OBSERVATION_DISTRIBUTION
BINOMIAL   INF_BOUND : 0   SUP_BOUND : 900   PROBABILITY : 0.1

STATE 1 OBSERVATION_DISTRIBUTION
BINOMIAL   INF_BOUND : 0   SUP_BOUND : 900   PROBABILITY : 0.5

STATE 2 OBSERVATION_DISTRIBUTION
BINOMIAL   INF_BOUND : 0   SUP_BOUND : 900   PROBABILITY : 0.9


OUTPUT_PROCESS 2 : PARAMETRIC

STATE 0 OBSERVATION_DISTRIBUTION
BINOMIAL   INF_BOUND : 0   SUP_BOUND : 15   PROBABILITY : 0.1

STATE 1 OBSERVATION_DISTRIBUTION
BINOMIAL   INF_BOUND : 0   SUP_BOUND : 15   PROBABILITY : 0.5

STATE 2 OBSERVATION_DISTRIBUTION
BINOMIAL   INF_BOUND : 0   SUP_BOUND : 15   PROBABILITY : 0.9
