
# This file has been generated at Thu Dec 18 12:08:20 2008

from openalea.core import *


__name__ = 'Demo.ChangePoint'

__editable__ = True
__description__ = 'Change point detection.'
__license__ = ''
__url__ = ''
__alias__ = []
__version__ = '0.1'
__authors__ = 'Y. Guedon'
__institutes__ = 'CIRAD'
__icon__ = ''
 

__all__ = ['_48848016', '_48847984', '_48847952', '_48847888']


_48848016 = DataFactory(name='angelique_internode_length.seq', 
                    description='Credits Y. Caraglio', 
                    editors=None,
                    includes=None,
                    )


_48847984 = DataFactory(name='pin_laricio_7x.seq', 
                    description='Credits: C. Meredieu, Y. Caraglio', 
                    editors=None,
                    includes=None,
                    )



_48847952 = CompositeNodeFactory(name='Dycorinia change point', 
                             description='Analysis of the successive internode lengths of Dycorinia guinensis.', 
                             category='STAT,composite,demo',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('vplants.stat', 'Load_from_file'),
   4: ('openalea.data structure', 'int'),
   6: ('vplants.stat', 'PlotSegmentProfile (gnuplot)'),
   7: ('vplants.stat', 'SelectVariable'),
   8: ('vplants.stat', 'SelectVariable'),
   9: ('vplants.stat', 'Segmentation'),
   10: ('vplants.stat', 'Segmentation'),
   11: ('openalea.data structure', '#string'),
   12: ('openalea.data structure', '#string'),
   13: ('vplants.stat', 'Segmentation'),
   14: ('openalea.data structure', '#string'),
   15: ('openalea.data structure', 'int'),
   16: ('vplants.stat', 'SelectVariable'),
   17: ('vplants.stat', 'Merge'),
   18: ('vplants.stat', 'PlotData (gnuplot)'),
   21: ('vplants.stat', 'Segmentation'),
   22: ('openalea.data structure', 'int'),
   23: ('openalea.data structure', 'int'),
   24: ('openalea.data structure', '#string'),
   25: ('vplants.stat', 'SelectVariable'),
   26: ('vplants.stat', 'PlotSegmentProfile (gnuplot)'),
   27: ('openalea.data structure', '#string'),
   28: ('vplants.stat', 'PlotSegmentProfile (gnuplot)'),
   29: ('openalea.data structure', '#string'),
   30: ('openalea.data structure', 'int'),
   31: ('Demo.ChangePoint', 'angelique_internode_length.seq'),
   33: ('system', 'annotation'),
   34: ('system', 'annotation'),
   35: ('system', 'annotation'),
   37: ('system', 'annotation'),
   39: ('system', 'annotation'),
   40: ('system', 'annotation'),
   41: ('system', 'annotation')},
                             elt_connections={  9792980: (2, 0, 21, 0),
   9792992: (17, 0, 18, 0),
   9793004: (9, 0, 8, 0),
   9793016: (27, 0, 26, 3),
   9793028: (7, 0, 17, 0),
   9793040: (29, 0, 6, 3),
   9793052: (2, 0, 13, 0),
   9793064: (21, 0, 25, 0),
   9793076: (4, 0, 6, 1),
   9793088: (16, 0, 17, 0),
   9793100: (11, 0, 9, 5),
   9793112: (23, 0, 28, 2),
   9793124: (2, 0, 10, 0),
   9793136: (24, 0, 28, 3),
   9793148: (15, 0, 9, 1),
   9793160: (2, 0, 28, 0),
   9793172: (15, 0, 10, 1),
   9793184: (2, 0, 9, 0),
   9793196: (31, 0, 2, 0),
   9793208: (30, 0, 6, 2),
   9793220: (15, 0, 13, 1),
   9793232: (13, 0, 16, 0),
   9793244: (12, 0, 10, 5),
   9793256: (10, 0, 7, 0),
   9793268: (23, 0, 21, 2),
   9793280: (2, 0, 6, 0),
   9793292: (22, 0, 28, 1),
   9793304: (25, 0, 26, 0),
   9793316: (14, 0, 13, 5),
   9793328: (8, 0, 17, 0),
   9793340: (24, 0, 21, 5),
   9793364: (22, 0, 21, 1)},
                             elt_data={  2: {  'block': False,
         'caption': 'SEQUENCES',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 183.75,
         'posy': 35.0,
         'priority': 0,
         'user_application': None},
   4: {  'block': False,
         'caption': '1',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 466.25,
         'posy': 11.25,
         'priority': 0,
         'user_application': None},
   6: {  'block': False,
         'caption': 'PlotSegmentProfile (gnuplot)',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 410.0,
         'posy': 70.0,
         'priority': 0,
         'user_application': None},
   7: {  'block': False,
         'caption': 'SelectVariable',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([2]),
         'posx': 296.25,
         'posy': 333.75,
         'priority': 0,
         'user_application': None},
   8: {  'block': False,
         'caption': 'SelectVariable',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([2]),
         'posx': 167.5,
         'posy': 335.0,
         'priority': 0,
         'user_application': None},
   9: {  'block': False,
         'caption': 'Segmentation',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([3, 4]),
         'posx': 123.75,
         'posy': 267.5,
         'priority': 0,
         'user_application': None},
   10: {  'block': False,
          'caption': 'Segmentation',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([3, 4, 7]),
          'posx': 275.0,
          'posy': 267.5,
          'priority': 0,
          'user_application': None},
   11: {  'block': False,
          'caption': "'Gaussian'",
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 192.5,
          'posy': 195.0,
          'priority': 0,
          'user_application': None},
   12: {  'block': False,
          'caption': "'Mean'",
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 323.75,
          'posy': 197.5,
          'priority': 0,
          'user_application': None},
   13: {  'block': False,
          'caption': 'Segmentation',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([3, 4, 7]),
          'posx': 402.5,
          'posy': 263.75,
          'priority': 0,
          'user_application': None},
   14: {  'block': False,
          'caption': "'Variance'",
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 433.75,
          'posy': 198.75,
          'priority': 0,
          'user_application': None},
   15: {  'block': False,
          'caption': '1',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 292.5,
          'posy': 197.5,
          'priority': 0,
          'user_application': None},
   16: {  'block': False,
          'caption': 'SelectVariable',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([2]),
          'posx': 421.25,
          'posy': 333.75,
          'priority': 0,
          'user_application': None},
   17: {  'block': False,
          'caption': 'Merge',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 327.5,
          'posy': 411.25,
          'priority': 0,
          'user_application': None},
   18: {  'block': False,
          'caption': 'PlotData (gnuplot)',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 290.0,
          'posy': 471.25,
          'priority': 0,
          'user_application': None},
   21: {  'block': False,
          'caption': 'Segmentation',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([3, 4]),
          'posx': 582.5,
          'posy': 243.75,
          'priority': 0,
          'user_application': None},
   22: {  'block': False,
          'caption': '1',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 663.75,
          'posy': 137.5,
          'priority': 0,
          'user_application': None},
   23: {  'block': False,
          'caption': '3',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 716.25,
          'posy': 137.5,
          'priority': 0,
          'user_application': None},
   24: {  'block': False,
          'caption': "'Mean'",
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 761.25,
          'posy': 133.75,
          'priority': 0,
          'user_application': None},
   25: {  'block': False,
          'caption': 'SelectVariable',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([2]),
          'posx': 615.0,
          'posy': 310.0,
          'priority': 0,
          'user_application': None},
   26: {  'block': False,
          'caption': 'PlotSegmentProfile (gnuplot)',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 640.0,
          'posy': 373.75,
          'priority': 0,
          'user_application': None},
   27: {  'block': False,
          'caption': "'Variance'",
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 762.5,
          'posy': 312.5,
          'priority': 0,
          'user_application': None},
   28: {  'block': False,
          'caption': 'PlotSegmentProfile (gnuplot)',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 755.0,
          'posy': 213.75,
          'priority': 0,
          'user_application': None},
   29: {  'block': False,
          'caption': "'Gaussian'",
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 555.0,
          'posy': 7.5,
          'priority': 0,
          'user_application': None},
   30: {  'block': False,
          'caption': '3',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 508.75,
          'posy': 10.0,
          'priority': 0,
          'user_application': None},
   31: {  'block': False,
          'caption': 'angelique_internode_length.seq',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([2]),
          'posx': 88.75,
          'posy': -46.25,
          'priority': 0,
          'user_application': None},
   33: {  'posx': 412.5,
          'posy': -78.75,
          'txt': 'Dycorinia guianensis main axis\ndescribed at the internode scale:\nGuassian change point model'},
   34: {'posx': 831.25, 'posy': -48.75, 'txt': 'Author : Yann Guedon'},
   35: {'posx': 825.0, 'posy': -25.0, 'txt': ' Credits : Yves Caraglio'},
   37: {  'posx': 262.5,
          'posy': 515.0,
          'txt': 'Comparison of the 3 Gaussian\nchange-point models'},
   39: {'posx': 791.25, 'posy': 252.5, 'txt': 'Change in the mean model'},
   40: {  'posx': 665.0,
          'posy': 66.25,
          'txt': 'Change in the mean and \nthe variance model'},
   41: {  'posx': 632.5,
          'posy': 427.5,
          'txt': 'Change in the the variance model'},
   '__in__': {  'caption': 'In',
                'hide': True,
                'lazy': True,
                'minimal': False,
                'port_hide_changed': set([]),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0},
   '__out__': {  'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'minimal': False,
                 'port_hide_changed': set([]),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0}},
                             elt_value={  2: [(1, "'SEQUENCES'")],
   4: [(0, '1')],
   6: [(4, "'Segment'")],
   7: [(1, '[1]'), (2, "'Keep'")],
   8: [(1, '[1]'), (2, "'Keep'")],
   9: [(2, '3'), (3, '[]'), (4, "''"), (6, "'Fixed'"), (7, "'Sequence'")],
   10: [(2, '3'), (3, '[]'), (4, "''"), (6, "'Fixed'"), (7, "'Sequence'")],
   11: [(0, "'Gaussian'")],
   12: [(0, "'Mean'")],
   13: [(2, '3'), (3, '[]'), (4, "''"), (6, "'Fixed'"), (7, "'Sequence'")],
   14: [(0, "'Variance'")],
   15: [(0, '1')],
   16: [(1, '[1]'), (2, "'Keep'")],
   17: [],
   18: [],
   21: [(3, '[]'), (4, "''"), (6, "'Fixed'"), (7, "'Residual'")],
   22: [(0, '1')],
   23: [(0, '3')],
   24: [(0, "'Mean'")],
   25: [(1, '[2]'), (2, "'Keep'")],
   26: [(1, '1'), (2, '3'), (4, "'Segment'")],
   27: [(0, "'Variance'")],
   28: [(4, "'Segment'")],
   29: [(0, "'Gaussian'")],
   30: [(0, '3')],
   31: [  (  0,
             'PackageData(Demo.ChangePoint, angelique_internode_length.seq)'),
          (1, 'None'),
          (2, 'None')],
   33: [],
   34: [],
   35: [],
   37: [],
   39: [],
   40: [],
   41: [],
   '__in__': [],
   '__out__': []},
                             lazy=True,
                             )




_48847888 = CompositeNodeFactory(name='Corsican pine change point', 
                             description='', 
                             category='Stat,composite,demo',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('vplants.stat', 'Load_from_file'),
   3: ('vplants.stat', 'PlotSegmentProfile (gnuplot)'),
   4: ('vplants.stat', 'Cluster'),
   5: ('vplants.stat', 'SelectVariable'),
   6: ('vplants.stat', 'PlotSegmentProfile (gnuplot)'),
   7: ('vplants.stat', 'Segmentation'),
   8: ('vplants.stat', 'SelectVariable'),
   9: ('vplants.stat', 'SelectVariable'),
   10: ('vplants.stat', 'PlotData (gnuplot)'),
   11: ('vplants.stat', 'Segmentation'),
   12: ('vplants.stat', 'PlotData (gnuplot)'),
   13: ('vplants.stat', 'SegmentationSample'),
   14: ('vplants.stat', 'SelectIndividual'),
   15: ('vplants.stat', 'PlotData (gnuplot)'),
   16: ('openalea.data structure', 'int'),
   17: ('openalea.data structure', 'int'),
   18: ('vplants.stat', 'SegmentationSample'),
   19: ('vplants.stat', 'ComputeCorrelation multivariate'),
   20: ('vplants.stat', 'Plot (gnuplot)'),
   21: ('vplants.stat', 'SelectVariable'),
   22: ('vplants.stat', 'PointwiseAverage'),
   23: ('vplants.stat', 'PlotData (gnuplot)'),
   24: ('vplants.stat', 'SelectIndividual'),
   25: ('vplants.stat', 'PlotData (gnuplot)'),
   26: ('vplants.stat', 'Vectors'),
   27: ('vplants.stat', 'Regression'),
   28: ('vplants.stat', 'Plot (gnuplot)'),
   29: ('openalea.flow control', 'annotation'),
   30: ('openalea.flow control', 'annotation'),
   31: ('openalea.flow control', 'annotation'),
   32: ('openalea.flow control', 'annotation'),
   33: ('openalea.flow control', 'annotation'),
   34: ('Demo.ChangePoint', 'pin_laricio_7x.seq'),
   36: ('openalea.flow control', 'annotation'),
   37: ('openalea.flow control', 'annotation'),
   38: ('openalea.flow control', 'annotation'),
   41: ('openalea.flow control', 'annotation'),
   42: ('openalea.flow control', 'annotation'),
   43: ('openalea.flow control', 'annotation'),
   44: ('openalea.flow control', 'annotation'),
   45: ('openalea.flow control', 'annotation')},
                             elt_connections={  9790396: (8, 0, 12, 0),
   9790408: (22, 0, 24, 0),
   9790420: (19, 0, 20, 0),
   9790432: (5, 0, 13, 0),
   9790444: (2, 0, 25, 0),
   9790456: (17, 0, 14, 1),
   9790468: (7, 0, 9, 0),
   9790480: (27, 0, 28, 0),
   9790492: (4, 0, 6, 0),
   9790504: (5, 0, 11, 0),
   9790516: (5, 0, 18, 0),
   9790528: (2, 0, 4, 0),
   9790540: (21, 0, 26, 0),
   9790552: (5, 0, 7, 0),
   9790564: (18, 0, 21, 0),
   9790576: (14, 0, 15, 0),
   9790588: (9, 0, 10, 0),
   9790600: (26, 0, 27, 0),
   9790612: (16, 0, 14, 1),
   9790624: (34, 0, 2, 0),
   9790636: (5, 0, 3, 0),
   9790648: (11, 0, 8, 0),
   9790660: (4, 0, 5, 0),
   9790672: (13, 0, 14, 0),
   9790684: (18, 0, 19, 0),
   9790696: (24, 0, 23, 0),
   9790708: (21, 0, 22, 0)},
                             elt_data={  2: {  'block': False,
         'caption': 'SEQUENCES',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 113.75,
         'posy': 86.25,
         'priority': 0,
         'user_application': None},
   3: {  'block': False,
         'caption': 'Plot',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 385.0,
         'posy': 251.25,
         'priority': 0,
         'user_application': None},
   4: {  'block': False,
         'caption': 'Cluster',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 140.0,
         'posy': 160.0,
         'priority': 0,
         'user_application': None},
   5: {  'block': False,
         'caption': 'SelectVariable',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 125.0,
         'posy': 256.25,
         'priority': 0,
         'user_application': None},
   6: {  'block': False,
         'caption': 'Plot',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 378.75,
         'posy': 178.75,
         'priority': 0,
         'user_application': None},
   7: {  'block': False,
         'caption': 'Segmentation',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([3, 4, 6, 7]),
         'posx': -48.75,
         'posy': 323.75,
         'priority': 0,
         'user_application': None},
   8: {  'block': False,
         'caption': 'SelectVariable',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 201.25,
         'posy': 385.0,
         'priority': 0,
         'user_application': None},
   9: {  'block': False,
         'caption': 'SelectVariable',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': -23.75,
         'posy': 372.5,
         'priority': 0,
         'user_application': None},
   10: {  'block': False,
          'caption': 'PlotData (gnuplot)',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': -35.0,
          'posy': 420.0,
          'priority': 0,
          'user_application': None},
   11: {  'block': False,
          'caption': 'Segmentation',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([2, 4, 6, 7]),
          'posx': 173.75,
          'posy': 328.75,
          'priority': 0,
          'user_application': None},
   12: {  'block': False,
          'caption': 'PlotData (gnuplot)',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 188.75,
          'posy': 436.25,
          'priority': 0,
          'user_application': None},
   13: {  'block': False,
          'caption': 'SegmentationSample',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 363.75,
          'posy': 331.25,
          'priority': 0,
          'user_application': None},
   14: {  'block': False,
          'caption': 'SelectIndividual',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 411.25,
          'posy': 441.25,
          'priority': 0,
          'user_application': None},
   15: {  'block': False,
          'caption': 'PlotData (gnuplot)',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 403.75,
          'posy': 491.25,
          'priority': 0,
          'user_application': None},
   16: {  'block': False,
          'caption': '4',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 458.75,
          'posy': 371.25,
          'priority': 0,
          'user_application': None},
   17: {  'block': False,
          'caption': '5',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 505.0,
          'posy': 371.25,
          'priority': 0,
          'user_application': None},
   18: {  'block': False,
          'caption': 'SegmentationSample',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 572.5,
          'posy': 325.0,
          'priority': 0,
          'user_application': None},
   19: {  'block': False,
          'caption': 'ComputeCorrelation multivariate',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 760.0,
          'posy': 388.75,
          'priority': 0,
          'user_application': None},
   20: {  'block': False,
          'caption': 'Plot (gnuplot)',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 857.5,
          'posy': 443.75,
          'priority': 0,
          'user_application': None},
   21: {  'block': False,
          'caption': 'SelectVariable',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 578.75,
          'posy': 397.5,
          'priority': 0,
          'user_application': None},
   22: {  'block': False,
          'caption': 'PointwiseAverage',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 671.25,
          'posy': 507.5,
          'priority': 0,
          'user_application': None},
   23: {  'block': False,
          'caption': 'PlotData (gnuplot)',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 793.75,
          'posy': 617.5,
          'priority': 0,
          'user_application': None},
   24: {  'block': False,
          'caption': 'SelectIndividual',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 793.75,
          'posy': 568.75,
          'priority': 0,
          'user_application': None},
   25: {  'block': False,
          'caption': 'PlotData (gnuplot)',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 351.25,
          'posy': 71.25,
          'priority': 0,
          'user_application': None},
   26: {  'block': False,
          'caption': 'Vectors',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 655.0,
          'posy': 565.0,
          'priority': 0,
          'user_application': None},
   27: {  'block': False,
          'caption': 'Regression',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 518.75,
          'posy': 627.5,
          'priority': 0,
          'user_application': None},
   28: {  'block': False,
          'caption': 'Plot (gnuplot)',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 585.0,
          'posy': 681.25,
          'priority': 0,
          'user_application': None},
   29: {  'posx': 123.47222222222223,
          'posy': 0.69444444444445175,
          'txt': 'Source file'},
   30: {'posx': 641.25, 'posy': 72.5, 'txt': 'Packages : VPlants.Stat'},
   31: {'posx': 643.75, 'posy': 101.25, 'txt': 'Authors : Yann Guedon'},
   32: {  'posx': 641.25,
          'posy': 127.5,
          'txt': 'Credits : Celine Meredieu, Yves Caraglio '},
   33: {  'posx': 527.5,
          'posy': -22.5,
          'txt': 'Corsican pine tree trunks described at the annual shoot scale: \nGaussian change-point models'},
   34: {  'block': False,
          'caption': 'pin_laricio_7x.seq',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([2]),
          'posx': -23.75,
          'posy': -3.75,
          'priority': 0,
          'user_application': None},
   36: {  'posx': -40.0,
          'posy': 472.5,
          'txt': 'Gaussian change-point\n model represented \nby a step function'},
   37: {'posx': 198.75, 'posy': 486.25, 'txt': 'Suboptimal\nsegmentation'},
   38: {  'posx': 407.5,
          'posy': 536.25,
          'txt': 'Segmentation of\n2 individuals'},
   41: {  'posx': 872.5,
          'posy': 481.25,
          'txt': 'Autocorrelation function\ncomputed from the \nresidual sequences'},
   42: {'posx': 391.25, 'posy': 116.25, 'txt': 'Input data'},
   43: {'posx': 526.25, 'posy': 185.0, 'txt': 'Bivariate change-point model'},
   44: {'posx': 535.0, 'posy': 251.25, 'txt': 'Univariate change-point model'},
   45: {  'posx': 740.0,
          'posy': 676.25,
          'txt': 'Pointwise average\nreisual sequence'},
   '__in__': {  'caption': 'In',
                'hide': True,
                'lazy': True,
                'minimal': False,
                'port_hide_changed': set([]),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0},
   '__out__': {  'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'minimal': False,
                 'port_hide_changed': set([]),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0}},
                             elt_value={  2: [(1, "'SEQUENCES'")],
   3: [(1, '2'), (2, '5'), (3, "'Gaussian'"), (4, "'Segment'")],
   4: [(1, "'Step'"), (2, '1'), (3, '10'), (4, '0.0'), (5, '[None]')],
   5: [(1, '[1]'), (2, "'Keep'")],
   6: [(1, '5'), (2, '4'), (3, "'Gaussian, Gaussian'"), (4, "'Segment'")],
   7: [  (1, '2'),
         (2, '10'),
         (3, 'None'),
         (4, "''"),
         (5, "'Gaussian'"),
         (6, "'Estimated'"),
         (7, "'Sequence'")],
   8: [(1, '[2, 3]'), (2, "'Keep'")],
   9: [(1, '[2, 3]'), (2, "'Keep'")],
   10: [],
   11: [  (1, '2'),
          (2, 'None'),
          (3, '[1936, 1943, 1961, 1986]'),
          (4, "''"),
          (5, "'Gaussian'"),
          (6, "'Estimated'"),
          (7, "'Sequence'")],
   12: [],
   13: [  (1, '[5, 6, 6, 4, 4, 4]'),
          (2, "''"),
          (3, "'Gaussian'"),
          (4, "'Sequence'")],
   14: [(2, "'Keep'")],
   15: [],
   16: [(0, '4')],
   17: [(0, '5')],
   18: [  (1, '[5, 6, 6, 4, 4, 4]'),
          (2, "''"),
          (3, "'Gaussian'"),
          (4, "'Residual'")],
   19: [  (1, 'True'),
          (2, '2'),
          (3, 'None'),
          (4, '20'),
          (5, "'Pearson'"),
          (6, "'Exact'")],
   20: [],
   21: [(1, '[2]'), (2, "'Keep'")],
   22: [(1, 'True'), (2, "'Sequence'"), (3, "''"), (4, "''"), (5, "'ASCII'")],
   23: [],
   24: [(1, '[0, 7]'), (2, "'Keep'")],
   25: [],
   26: [(1, 'False')],
   27: [  (1, "'MovingAverage'"),
          (2, '1'),
          (3, '2'),
          (4, '[1]'),
          (5, '[]'),
          (6, 'None'),
          (7, '0.0'),
          (8, "'Averaging'"),
          (9, 'True')],
   28: [],
   29: [],
   30: [],
   31: [],
   32: [],
   33: [],
   34: [  (0, 'PackageData(Demo.ChangePoint, pin_laricio_7x.seq)'),
          (1, 'None'),
          (2, 'None')],
   36: [],
   37: [],
   38: [],
   41: [],
   42: [],
   43: [],
   44: [],
   45: [],
   '__in__': [],
   '__out__': []},
                             lazy=True,
                             )




