# -*-python-*-

from openalea.sconsx import config, environ
import os

pj = os.path.join
ALEASolution = config.ALEASolution

options = Variables(['../options.py', 'options.py'], ARGUMENTS)
tools = ['qt4','opengl','readline']

env = ALEASolution(options, tools)
prefix = env['build_prefix']

# Build stage
env.SConscript(pj(prefix,"src/cpp/SConscript"), 
           exports="env")
Default("build")

