
{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set name = pyproject.get('project').get('name') %}
{% set description = pyproject.get('project').get('description') %}
{% set version = environ.get('SETUPTOOLS_SCM_PRETEND_VERSION', "0.0.0.dev") %}
{% set license = pyproject.get('project').get('license') %}
{% set home = pyproject.get('project', {}).get('urls', {}).get('Homepage', '') %}
{% set build_deps = pyproject.get("build-system", {}).get("requires", []) %}
{% set deps = pyproject.get('project', {}).get('dependencies', []) %}
{% set conda_deps = pyproject.get('tool', {}).get('conda', {}).get('environment', {}).get('dependencies',[]) %}
{% set test_deps = pyproject.get('project', {}).get('optional-dependencies', {}).get('test',[]) %}



package:
  name: {{ name }}
  version: {{ version }}


source:
  path: ..

build:
  number: 0
  preserve_egg_dir: True

  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-build-isolation -vv  

requirements:
  host:
    - python
    {% for dep in build_deps %}
    - {{ dep }}
    {% endfor  %}
    - boost
    - scikit-build-core
    - numpy

  build:
    - {{ compiler("cxx") }}
    - cmake
    - make                                 # [not win]

  run:
    - python
    {% for dep in deps + conda_deps %}
    - {{ dep }}
    {% endfor %}




test:
  imports:
    - openalea.stat_tool
  requires:

    {% for dep in test_deps %}
    - {{ dep }}
    {% endfor %}

  source_files:
    - test/
  commands:
    - cd test
    - pytest -v --ignore=aml          # [not win]
    - pytest -v test_cluster.py test_comparison.py test_distribution.py test_histogram.py test_mixture.py   # [win]


about:
  home: {{ home }}
  summary: {{ description }}
  license: {{ license }}


extra:
  recipe-maintainers:
    - Jean-Baptiste Durand
    - Thomas Arsouze
    - Christophe Pradal
