# -*-python-*-

import os
bn = os.path.basename

Import( "env" )

lib_env = env.Clone()
lib_env.EnableQt4Modules(['QtCore','QtOpenGL', 'QtGui'])

# Import / Export symbols for windows dll
if lib_env['compiler'] == 'mingw':
    LINKFLAGS=["-enable-stdcall-fixup",
               "-enable-auto-import",
               "-enable-runtime-pseudo-reloc",
               "-s"]
    lib_env.AppendUnique(LINKFLAGS=LINKFLAGS)
    

includes= lib_env.ALEAGlob('*.h')
includes += lib_env.ALEAGlob('*.hpp')
sources = lib_env.ALEAGlob('*.cpp')

# files to exclude from sources
excludes = Split( """
""")

for f in excludes: 
    for cpp in sources:
	if f in cpp:
            sources.remove(cpp)
	    break

lib_env.AppendUnique(LIBS=['vptool', 'vpstat_tool'])

lib_env.AppendUnique(CPPDEFINES=['MESSAGE'])
inc = lib_env.ALEAIncludes( "sequence_analysis", includes )

lib = lib_env.ALEALibrary( "vpsequence", 
                           sources, 
                           )

