# -*-python-*-

from openalea.sconsx import config, environ
import os
pj = os.path.join
ALEASolution = config.ALEASolution

options = Variables(['../options.py', 'options.py'], ARGUMENTS)
options.Add(BoolVariable('with_efence', 'build tests with efence library', 1))
options.Add(BoolVariable('DEBUG', 'my debug', 0))
# TODO: read from options.py
options.Add(BoolVariable('with_test', 'Add c++ tests', 1))

tools = ['boost_python', 'openalea.stattool']

env = ALEASolution(options, tools)
env.AppendUnique(CXXFLAGS=['-x', 'c++', '-std=c++0x'])

if env['with_efence']:
    env.AppendUnique(LIBS=['efence'])


# Build stage
prefix = env['build_prefix']
SConscript(pj(prefix,"src/cpp/SConscript"),
        exports='env')
SConscript(pj(prefix,"src/wrapper/SConscript"),
        exports='env')

SConscript(pj(prefix,"test/cpp/SConscript"), exports="env")

Default("build")

