
# This file has been generated at Mon Aug 24 14:33:19 2009

from openalea.core import *


__name__ = 'demo.stat_tool demos and tutorials'

__editable__ = True
__description__ = 'demonstrations and tutorials on stat_tool package'
__license__ = 'GPL'
__url__ = 'http://openalea.gforge.inria.fr/doc/vplants/stat_tool/doc/html/contents.html'
__alias__ = []
__version__ = '0.7.0'
__authors__ = 'T. Cokelaer'
__institutes__ = 'INRIA/CIRAD'
__icon__ = 'icon.png'


__all__ = ['_189916396', '_187770988']


_189916396 = DataFactory(name='angelique_internode_length.seq',
                    description='Credits Y. Caraglio',
                    editors=None,
                    includes=None,
                    )



_187770988 = CompositeNodeFactory(name='compound tutorial',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  20: ('vplants.stats', 'Plot (stat_tool)'),
   21: ('vplants.stats', 'Plot (stat_tool)'),
   22: ('vplants.stats', 'ExtractHistogram'),
   23: ('vplants.stats', 'ExtractData'),
   24: ('vplants.stats', 'ToDistribution'),
   25: ('vplants.stats', 'ToHistogram'),
   26: ('vplants.stats', 'ExtractDistribution'),
   27: ('vplants.stats', 'Plot (stat_tool)'),
   28: ('vplants.stats', 'EstimateCompound'),
   29: ('vplants.stats', 'Plot (stat_tool)'),
   30: ('openalea.flow control', 'annotation'),
   31: ('openalea.flow control', 'annotation'),
   32: ('openalea.flow control', 'annotation'),
   33: ('vplants.stats', 'Plot (stat_tool)'),
   34: ('vplants.stats', 'Plot (stat_tool)'),
   35: ('vplants.stats', 'Binomial'),
   36: ('vplants.stats', 'Compound'),
   37: ('vplants.stats', 'Plot (stat_tool)'),
   38: ('vplants.stats', 'ExtractDistribution'),
   39: ('vplants.stats', 'ExtractHistogram'),
   40: ('openalea.flow control', 'annotation'),
   41: ('vplants.stats', 'ExtractHistogram'),
   42: ('vplants.stats', 'Plot (stat_tool)'),
   43: ('vplants.stats', 'NegativeBinomial'),
   44: ('vplants.stats', 'Simulate(distribution)')},
                             elt_connections={  164490912: (25, 0, 21, 0),
   164490936: (22, 0, 20, 0),
   164490948: (26, 0, 25, 0),
   164490960: (23, 0, 22, 0),
   164490972: (28, 0, 23, 0),
   164490984: (36, 0, 39, 0),
   164490996: (41, 0, 34, 0),
   164491008: (43, 0, 36, 1),
   164491020: (44, 0, 28, 0),
   164491032: (28, 0, 27, 0),
   164491044: (39, 0, 33, 0),
   164491056: (36, 0, 44, 0),
   164491068: (36, 0, 41, 0),
   164491080: (36, 0, 38, 0),
   164491092: (35, 0, 36, 0),
   164491104: (43, 0, 29, 0),
   164491116: (28, 0, 26, 0),
   164491128: (36, 0, 37, 0),
   164491140: (44, 0, 42, 0),
   164491152: (35, 0, 29, 0),
   164491164: (38, 0, 28, 1)},
                             elt_data={  20: {  'block': False,
          'caption': 'Plot (stat_tool)',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 357.5,
          'posy': 417.5,
          'priority': 0,
          'user_application': None},
   21: {  'block': False,
          'caption': 'Plot (stat_tool)',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 793.75,
          'posy': 416.25,
          'priority': 0,
          'user_application': None},
   22: {  'block': False,
          'caption': 'ExtractHistogram',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 316.25,
          'posy': 350.0,
          'priority': 0,
          'user_application': None},
   23: {  'block': False,
          'caption': 'ExtractData',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 308.75,
          'posy': 292.5,
          'priority': 0,
          'user_application': None},
   24: {  'block': False,
          'caption': 'ToDistribution',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 780.0,
          'posy': 157.5,
          'priority': 0,
          'user_application': None},
   25: {  'block': False,
          'caption': 'ToHistogram',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 781.25,
          'posy': 353.75,
          'priority': 0,
          'user_application': None},
   26: {  'block': False,
          'caption': 'ExtractDistribution',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 761.25,
          'posy': 275.0,
          'priority': 0,
          'user_application': None},
   27: {  'block': False,
          'caption': 'Plot (stat_tool)',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 526.25,
          'posy': 283.75,
          'priority': 0,
          'user_application': None},
   28: {  'block': False,
          'caption': 'EstimateCompound, cdist2',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 438.75,
          'posy': 205.0,
          'priority': 0,
          'user_application': None},
   29: {  'block': False,
          'caption': 'Plot (stat_tool)',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 28.75,
          'posy': -185.0,
          'priority': 0,
          'user_application': None},
   30: {  'posx': 388.56757880018642,
          'posy': -338.17578800186368,
          'txt': 'Packages : VPlants.Stat_tool'},
   31: {  'posx': 391.06757880018642,
          'posy': -308.17578800186368,
          'txt': 'Authors : Thomas Cokelaer'},
   32: {  'posx': 388.56757880018642,
          'posy': -283.17578800186368,
          'txt': 'Credits : Yann Guedon'},
   33: {  'block': False,
          'caption': 'Plot (stat_tool)',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 652.5,
          'posy': 26.25,
          'priority': 0,
          'user_application': None},
   34: {  'block': False,
          'caption': 'Plot (stat_tool)',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 482.5,
          'posy': 31.25,
          'priority': 0,
          'user_application': None},
   35: {  'block': False,
          'caption': 'Binomial',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 63.75,
          'posy': -288.75,
          'priority': 0,
          'user_application': None},
   36: {  'block': False,
          'caption': 'Compound',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 181.25,
          'posy': -181.25,
          'priority': 0,
          'user_application': None},
   37: {  'block': False,
          'caption': 'Plot (stat_tool)',
          'hide': True,
          'lazy': False,
          'port_hide_changed': set([]),
          'posx': 108.75,
          'posy': -55.0,
          'priority': 0,
          'user_application': None},
   38: {  'block': False,
          'caption': 'ExtractDistribution',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 218.75,
          'posy': 100.0,
          'priority': 0,
          'user_application': None},
   39: {  'block': False,
          'caption': 'ExtractHistogram',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 638.75,
          'posy': -55.0,
          'priority': 0,
          'user_application': None},
   40: {  'posx': 393.56757880018642,
          'posy': -250.67578800186368,
          'txt': 'Source: based on a subset of stat_tool_test.aml'},
   41: {  'block': False,
          'caption': 'ExtractHistogram',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 465.0,
          'posy': -55.0,
          'priority': 0,
          'user_application': None},
   42: {  'block': False,
          'caption': 'Plot (stat_tool)',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 311.25,
          'posy': 28.75,
          'priority': 0,
          'user_application': None},
   43: {  'block': False,
          'caption': 'NegativeBinomial',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 182.5,
          'posy': -292.5,
          'priority': 0,
          'user_application': None},
   44: {  'block': False,
          'caption': 'Simulate(distribution)',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 268.75,
          'posy': -55.0,
          'priority': 0,
          'user_application': None},
   '__in__': {  'caption': 'In',
                'hide': True,
                'lazy': True,
                'minimal': False,
                'port_hide_changed': set([]),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0},
   '__out__': {  'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'minimal': False,
                 'port_hide_changed': set([]),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0}},
                             elt_value={  20: [  (  0,
             '<openalea.stat_tool._stat_tool._DistributionData object at 0xbe1a25c>'),
          (1, '7'),
          (2, "'Simulate'")],
   21: [(1, '8'), (2, "'Simulate'")],
   22: [(1, "'Sum'")],
   23: [],
   24: [(0, 'None')],
   25: [],
   26: [(1, "'Sum'"), (2, 'None')],
   27: [(1, '6'), (2, "'Estimate Compound'")],
   28: [  (2, "'Sum'"),
          (3, "'Likelihood'"),
          (4, 'None'),
          (5, '0'),
          (6, '-1'),
          (7, "'SecondDifference'"),
          (8, '-1.0'),
          (9, "'Zero'")],
   29: [(1, '1'), (2, "'Distribution'")],
   30: [],
   31: [],
   32: [],
   33: [(1, '5'), (2, "'Elementary'")],
   34: [(1, '4'), (2, "'Sum'")],
   35: [(0, '0'), (1, '10'), (2, '0.5')],
   36: [],
   37: [(1, '2'), (2, "'Compound'")],
   38: [(1, "'Sum'"), (2, 'None')],
   39: [(1, "'Sum'")],
   40: [],
   41: [(1, "'Sum'")],
   42: [(1, '3'), (2, "'Simulate'")],
   43: [(0, '0'), (1, '10.0'), (2, '0.5')],
   44: [(1, '100')],
   '__in__': [],
   '__out__': []},
                             lazy=True,
                             )




