# -*-python-*-

from openalea.sconsx import config, environ
import os

pj = os.path.join
ALEASolution = config.ALEASolution

options = Variables(['../options.py', 'options.py'], ARGUMENTS)

# Dependencies
common_tools = ['vplants.mtg', 'vplants.tool', 'vplants.plantgl',
                'vplants.amlobj', 'vplants.stat_tool', 'boost_python', 'qt4']

tools = ['alea', 'install'] + common_tools

env = ALEASolution(options, tools)
env.Append(CPPPATH=pj('$build_includedir', 'tree_matching'))

prefix = env['build_prefix']

# Build stage
SConscript(pj(prefix, "src/cpp/SConscript"),
           exports='env')

Default("build")
