# -*-python-*-
Import( "env" )

lib_env = env.Clone()

lib_env.EnableQt4Modules(['QtCore','QtOpenGL', 'QtGui'])

includes = lib_env.ALEAGlob('*.h')

sources= lib_env.ALEAGlob('*.cpp')

# Add defines to export symbols on Windows
DEFINES= list(lib_env['CPPDEFINES'])
DEFINES.append('VPTOOLS_MAKEDLL')

inc = lib_env.ALEAIncludes("tool", includes)

lib = lib_env.ALEALibrary("vptool", 
                          sources, 
                          CPPDEFINES = DEFINES)





