#include <boost/python.hpp>

void _stat_tool_convolution_threshold();
void _stat_tool_convolution_difference_weight();
void _stat_tool_gamma_max_nb_iteration();
void _stat_tool_categorical_process();
void _stat_tool_i_default();
void _stat_tool_gaussian_tail();
void _stat_tool_cumul_threshold();
void _stat_tool_multi_plot_set();
void _stat_tool_stat_error();
void _stat_tool_metric();
void _stat_tool_state_type();
void _stat_tool_chi2_frequency();
void _stat_tool_mixture_nb_vector();
void _stat_tool_curves();
void _stat_tool_bisection_ratio_threshold();
void _stat_tool();
void _stat_tool_model_type();
void _stat_tool_reestimation_f60cafa77afa5aac836b75ac8099ad5f();
void _stat_tool_plot_ymargin();
void _stat_tool_tying_rule();
void _stat_tool_variable_type();
void _stat_tool_convolution_nb_iter();
void _stat_tool_isolation_scale();
void _stat_tool_mixture_coeff();
void _stat_tool_bisection_nb_iter();
void _stat_tool_nb_error();
void _stat_tool_hierarchical_strategy();
void _stat_tool_observation_threshold();
void _stat_tool_ascii_space();
void _stat_tool_spreadsheet_roundness();
void _stat_tool_parametric_function();
void _stat_tool_gaussian_nb_sub_step();
void _stat_tool_plot_mass_threshold();
void _stat_tool_plot_shift();
void _stat_tool_gamma_frequency_threshold();
void _stat_tool_convolution_likelihood_diff();
void _stat_tool_chain();
void _stat_tool_max_value_coeff();
void _stat_tool_gamma_default_scale_parameter();
void _stat_tool_display_nb_individual();
void _stat_tool_single_plot();
void _stat_tool_noise_probability();
void _stat_tool_max_weight_step();
void _stat_tool_ascii_nb_value();
void _stat_tool_histogram();
void _stat_tool_nb_assignment_parameter();
void _stat_tool_renewal_difference_weight();
void _stat_tool_degree_decimal_scale();
void _stat_tool_max_surface();
void _stat_tool_side_effect();
void _stat_tool_estimation_criterion();
void _stat_tool_display_contingency_nb_value();
void _stat_tool_rounding();
void _stat_tool_contingency_nb_value();
void _stat_tool_skewness_roundness();
void _stat_tool_stat_tool_key_word();
void _stat_tool_penalty_type();
void _stat_tool_order();
void _stat_tool_posterior_probability_nb_vector();
void _stat_tool_line_nb_character();
void _stat_tool_max_nb_assignment();
void _stat_tool_gaussian_min_variation_coeff();
void _stat_tool_compound_init_probability();
void _stat_tool_d_default();
void _stat_tool_observation_process();
void _stat_tool_ascii_roundness();
void _stat_tool_plot_nb_distribution();
void _stat_tool_max_frequency();
void _stat_tool_discrete_parametric_process();
void _stat_tool_plot_nb_histogram();
void _stat_tool_threshold_direction();
void _stat_tool_convolution_nb_distribution();
void _stat_tool_regression_kernel();
void _stat_tool_sup_bound_margin();
void _stat_tool_variance_analysis_nb_value();
void _stat_tool_column_width();
void _stat_tool_gaussian_nb_step();
void _stat_tool_d_inf();
void _stat_tool_output_format();
void _stat_tool_distribution_transformation();
void _stat_tool_plot_nb_value();
void _stat_tool_stat_tool_parsing();
void _stat_tool_discrete_mixture_nb_iter();
void _stat_tool_renewal_likelihood_diff();
void _stat_tool_error_length();
void _stat_tool_ascii_nb_individual();
void _stat_tool_reestimation_56c13912c505596b9c1abb0933dddae9();
void _stat_tool_nb_threshold();
void _stat_tool_accessibility_threshold();
void _stat_tool_mixture_likelihood_diff();
void _stat_tool_min_probability();
void _stat_tool_neighborhood();
void _stat_tool_nb_value();
void _stat_tool_variable_nature();
void _stat_tool_nb_output_process();
void _stat_tool_histogram_frequency();
void _std_vector_353b4937bfcd5df4a175ee4ce86cc65e();
void _std_vector_b06d46b7ec9f551293bc27dc0a196afa();
void _stat_tool_discrete_mixture_nb_component();
void _stat_tool_observation_coeff();
void _stat_tool_interval_bisection();
void _stat_tool_compound_threshold();
void _stat_tool_min_nb_element();
void _stat_tool_tic_threshold();
void _stat_tool_inverse_gaussian_nb_sub_step();
void _stat_tool_global_nb_iter();
void _stat_tool_nb_value_coeff();
void _stat_tool_gamma_iteration_factor();
void _stat_tool_plot_range_ratio();
void _stat_tool_compound_difference_weight();
void _stat_tool_distribution_computation();
void _stat_tool_vector_nb_variable();
void _stat_tool_marginal_distribution_max_value();
void _stat_tool_nb_critical_probability();
void _stat_tool_p_threshold();
void _stat_tool_gaussian_max_nb_decimal();
void _stat_tool_inf_bound_margin();
void _stat_tool_process_distribution();
void _stat_tool_gamma_zero_frequency_threshold();
void _stat_tool_continuous_parametric();
void _stat_tool_max_diff_bound();
void _stat_tool_distribution();
void _stat_tool_nb_output();
void _stat_tool_mixture_nb_iter();
void _stat_tool_sample_nb_value_coeff();
void _stat_tool_correlation_type();
void _stat_tool_thresholding_factor();
void _stat_tool_vector_transformation();
void _stat_tool_min_weight_step();
void _stat_tool_error_type();
void _stat_tool_gamma_shape_parameter_threshold();
void _stat_tool_compound_distribution();
void _stat_tool_min_range();
void _stat_tool_latent_structure_algorithm();
void _stat_tool_process_type();
void _stat_tool_poisson_ratio();
void _stat_tool_mvmixture_likelihood_diff();
void _stat_tool_plot_roundness();
void _stat_tool_renewal_nb_iter();
void _stat_tool_sample_nb_value();
void _stat_tool_min_nb_assignment();
void _stat_tool_gamma_min_shape_parameter();
void _stat_tool_test_distribution();
void _stat_tool_poisson_range();
void _stat_tool_convolution_entropy_weight();
void _stat_tool_stat_interface();
void _stat_tool_distance_roundness();
void _stat_tool_gamma_nb_step();
void _stat_tool_max_range();
void _stat_tool_cluster_scale();
void _stat_tool_b_threshold();
void _stat_tool_inverse_gaussian_tail();
void _stat_tool_gamma_nb_sub_step();
void _stat_tool_nb_parameter();
void _stat_tool_compound_likelihood_diff();
void _stat_tool_nb_category();
void _stat_tool_count_pattern();
void _stat_tool_nb_state();
void _stat_tool_convolution_coeff();
void _stat_tool_von_mises_nb_sub_step();
void _stat_tool_inverse_gaussian_nb_step();
void _stat_tool_compound_nb_iter();
void _stat_tool_von_mises_nb_step();
void _stat_tool_stat_tool_error();
void _stat_tool_compound_entropy_weight();
void _stat_tool_test();
void _stat_tool_distance_nb_vector();
void _stat_tool_curve_transformation();
void _stat_tool_gamma_tail();
void _stat_tool_model_selection_criterion();
void _stat_tool_duration_distribution_mean_estimator();
void _stat_tool_display_conditional_nb_value();
void _stat_tool_mean_shift_coeff();
void _stat_tool_max_inf_bound();
void _std_vector_de5cf896f8255947948857862d989260();
void _stat_tool_angle_unit();
void _stat_tool_gamma_max_nb_decimal();
void _stat_tool_mixture_nb_component();
void _stat_tool_von_mises_concentration_computation();
void _stat_tool_partitioning_nb_iter_2();
void _stat_tool_plot_nb_curve();
void _stat_tool_censoring_estimator();
void _stat_tool_double_error();
void _stat_tool_continuous_parametric_process();
void _stat_tool_dist_nb_element();
void _stat_tool_plot_min_frequency();
void _stat_tool_stat_tool_label();
void _stat_tool_linkage();
void _stat_tool_frequency_distribution_transformation();
void _stat_tool_convolution_init_probability();
void _stat_tool_radian_decimal_scale();
void _stat_tool_accessibility_length();
void _stat_tool_nb_complete_interval();
void _stat_tool_partitioning_nb_iter_1();
void _stat_tool_yscale();
void _stat_tool_discrete_mixture_likelihood_diff();
void _stat_tool_max_mean();
void _stat_tool_multi_plot();
void _stat_tool_renewal_entropy_weight();
void _stat_tool_chain_reestimation_d32f0dcb03755b1b9b2e1e5e70c61c2e();
void _stat_tool_regression_nb_vector();
void _stat_tool_b_probability();
void _stat_tool_compound_coeff();
void _stat_tool_plot_max_shift();
void _stat_tool_moving_average_method();
void _stat_tool_negative_binomial_parameter();
void _stat_tool_multivariate_mixture();
void _stat_tool_distance_matrix();
void _stat_tool_vector_distance();
void _stat_tool_mixture();
void _stat_tool_chain_data();
void _stat_tool_discrete_parametric();
void _stat_tool_discrete_mixture();
void _stat_tool_dendrogram();
void _stat_tool_compound();
void _stat_tool_frequency_distribution();
void _stat_tool_regression();
void _stat_tool_convolution();
void _stat_tool_vectors();
void _stat_tool_compound_data();
void _stat_tool_forward();
void _stat_tool_multivariate_mixture_data();
void _stat_tool_clusters();
void _stat_tool_discrete_parametric_model();
void _stat_tool_discrete_distribution_data();
void _stat_tool_mixture_data();
void _stat_tool_convolution_data();
void _stat_tool_discrete_mixture_data();

BOOST_PYTHON_MODULE(__stat_tool)
{
    _stat_tool_convolution_threshold();
    _stat_tool_convolution_difference_weight();
    _stat_tool_gamma_max_nb_iteration();
    _stat_tool_categorical_process();
    _stat_tool_i_default();
    _stat_tool_gaussian_tail();
    _stat_tool_cumul_threshold();
    _stat_tool_multi_plot_set();
    _stat_tool_stat_error();
    _stat_tool_metric();
    _stat_tool_state_type();
    _stat_tool_chi2_frequency();
    _stat_tool_mixture_nb_vector();
    _stat_tool_curves();
    _stat_tool_bisection_ratio_threshold();
    _stat_tool();
    _stat_tool_model_type();
    _stat_tool_reestimation_f60cafa77afa5aac836b75ac8099ad5f();
    _stat_tool_plot_ymargin();
    _stat_tool_tying_rule();
    _stat_tool_variable_type();
    _stat_tool_convolution_nb_iter();
    _stat_tool_isolation_scale();
    _stat_tool_mixture_coeff();
    _stat_tool_bisection_nb_iter();
    _stat_tool_nb_error();
    _stat_tool_hierarchical_strategy();
    _stat_tool_observation_threshold();
    _stat_tool_ascii_space();
    _stat_tool_spreadsheet_roundness();
    _stat_tool_parametric_function();
    _stat_tool_gaussian_nb_sub_step();
    _stat_tool_plot_mass_threshold();
    _stat_tool_plot_shift();
    _stat_tool_gamma_frequency_threshold();
    _stat_tool_convolution_likelihood_diff();
    _stat_tool_chain();
    _stat_tool_max_value_coeff();
    _stat_tool_gamma_default_scale_parameter();
    _stat_tool_display_nb_individual();
    _stat_tool_single_plot();
    _stat_tool_noise_probability();
    _stat_tool_max_weight_step();
    _stat_tool_ascii_nb_value();
    _stat_tool_histogram();
    _stat_tool_nb_assignment_parameter();
    _stat_tool_renewal_difference_weight();
    _stat_tool_degree_decimal_scale();
    _stat_tool_max_surface();
    _stat_tool_side_effect();
    _stat_tool_estimation_criterion();
    _stat_tool_display_contingency_nb_value();
    _stat_tool_rounding();
    _stat_tool_contingency_nb_value();
    _stat_tool_skewness_roundness();
    _stat_tool_stat_tool_key_word();
    _stat_tool_penalty_type();
    _stat_tool_order();
    _stat_tool_posterior_probability_nb_vector();
    _stat_tool_line_nb_character();
    _stat_tool_max_nb_assignment();
    _stat_tool_gaussian_min_variation_coeff();
    _stat_tool_compound_init_probability();
    _stat_tool_d_default();
    _stat_tool_observation_process();
    _stat_tool_ascii_roundness();
    _stat_tool_plot_nb_distribution();
    _stat_tool_max_frequency();
    _stat_tool_discrete_parametric_process();
    _stat_tool_plot_nb_histogram();
    _stat_tool_threshold_direction();
    _stat_tool_convolution_nb_distribution();
    _stat_tool_regression_kernel();
    _stat_tool_sup_bound_margin();
    _stat_tool_variance_analysis_nb_value();
    _stat_tool_column_width();
    _stat_tool_gaussian_nb_step();
    _stat_tool_d_inf();
    _stat_tool_output_format();
    _stat_tool_distribution_transformation();
    _stat_tool_plot_nb_value();
    _stat_tool_stat_tool_parsing();
    _stat_tool_discrete_mixture_nb_iter();
    _stat_tool_renewal_likelihood_diff();
    _stat_tool_error_length();
    _stat_tool_ascii_nb_individual();
    _stat_tool_reestimation_56c13912c505596b9c1abb0933dddae9();
    _stat_tool_nb_threshold();
    _stat_tool_accessibility_threshold();
    _stat_tool_mixture_likelihood_diff();
    _stat_tool_min_probability();
    _stat_tool_neighborhood();
    _stat_tool_nb_value();
    _stat_tool_variable_nature();
    _stat_tool_nb_output_process();
    _stat_tool_histogram_frequency();
    _std_vector_353b4937bfcd5df4a175ee4ce86cc65e();
    _std_vector_b06d46b7ec9f551293bc27dc0a196afa();
    _stat_tool_discrete_mixture_nb_component();
    _stat_tool_observation_coeff();
    _stat_tool_interval_bisection();
    _stat_tool_compound_threshold();
    _stat_tool_min_nb_element();
    _stat_tool_tic_threshold();
    _stat_tool_inverse_gaussian_nb_sub_step();
    _stat_tool_global_nb_iter();
    _stat_tool_nb_value_coeff();
    _stat_tool_gamma_iteration_factor();
    _stat_tool_plot_range_ratio();
    _stat_tool_compound_difference_weight();
    _stat_tool_distribution_computation();
    _stat_tool_vector_nb_variable();
    _stat_tool_marginal_distribution_max_value();
    _stat_tool_nb_critical_probability();
    _stat_tool_p_threshold();
    _stat_tool_gaussian_max_nb_decimal();
    _stat_tool_inf_bound_margin();
    _stat_tool_process_distribution();
    _stat_tool_gamma_zero_frequency_threshold();
    _stat_tool_continuous_parametric();
    _stat_tool_max_diff_bound();
    _stat_tool_distribution();
    _stat_tool_nb_output();
    _stat_tool_mixture_nb_iter();
    _stat_tool_sample_nb_value_coeff();
    _stat_tool_correlation_type();
    _stat_tool_thresholding_factor();
    _stat_tool_vector_transformation();
    _stat_tool_min_weight_step();
    _stat_tool_error_type();
    _stat_tool_gamma_shape_parameter_threshold();
    _stat_tool_compound_distribution();
    _stat_tool_min_range();
    _stat_tool_latent_structure_algorithm();
    _stat_tool_process_type();
    _stat_tool_poisson_ratio();
    _stat_tool_mvmixture_likelihood_diff();
    _stat_tool_plot_roundness();
    _stat_tool_renewal_nb_iter();
    _stat_tool_sample_nb_value();
    _stat_tool_min_nb_assignment();
    _stat_tool_gamma_min_shape_parameter();
    _stat_tool_test_distribution();
    _stat_tool_poisson_range();
    _stat_tool_convolution_entropy_weight();
    _stat_tool_stat_interface();
    _stat_tool_distance_roundness();
    _stat_tool_gamma_nb_step();
    _stat_tool_max_range();
    _stat_tool_cluster_scale();
    _stat_tool_b_threshold();
    _stat_tool_inverse_gaussian_tail();
    _stat_tool_gamma_nb_sub_step();
    _stat_tool_nb_parameter();
    _stat_tool_compound_likelihood_diff();
    _stat_tool_nb_category();
    _stat_tool_count_pattern();
    _stat_tool_nb_state();
    _stat_tool_convolution_coeff();
    _stat_tool_von_mises_nb_sub_step();
    _stat_tool_inverse_gaussian_nb_step();
    _stat_tool_compound_nb_iter();
    _stat_tool_von_mises_nb_step();
    _stat_tool_stat_tool_error();
    _stat_tool_compound_entropy_weight();
    _stat_tool_test();
    _stat_tool_distance_nb_vector();
    _stat_tool_curve_transformation();
    _stat_tool_gamma_tail();
    _stat_tool_model_selection_criterion();
    _stat_tool_duration_distribution_mean_estimator();
    _stat_tool_display_conditional_nb_value();
    _stat_tool_mean_shift_coeff();
    _stat_tool_max_inf_bound();
    _std_vector_de5cf896f8255947948857862d989260();
    _stat_tool_angle_unit();
    _stat_tool_gamma_max_nb_decimal();
    _stat_tool_mixture_nb_component();
    _stat_tool_von_mises_concentration_computation();
    _stat_tool_partitioning_nb_iter_2();
    _stat_tool_plot_nb_curve();
    _stat_tool_censoring_estimator();
    _stat_tool_double_error();
    _stat_tool_continuous_parametric_process();
    _stat_tool_dist_nb_element();
    _stat_tool_plot_min_frequency();
    _stat_tool_stat_tool_label();
    _stat_tool_linkage();
    _stat_tool_frequency_distribution_transformation();
    _stat_tool_convolution_init_probability();
    _stat_tool_radian_decimal_scale();
    _stat_tool_accessibility_length();
    _stat_tool_nb_complete_interval();
    _stat_tool_partitioning_nb_iter_1();
    _stat_tool_yscale();
    _stat_tool_discrete_mixture_likelihood_diff();
    _stat_tool_max_mean();
    _stat_tool_multi_plot();
    _stat_tool_renewal_entropy_weight();
    _stat_tool_chain_reestimation_d32f0dcb03755b1b9b2e1e5e70c61c2e();
    _stat_tool_regression_nb_vector();
    _stat_tool_b_probability();
    _stat_tool_compound_coeff();
    _stat_tool_plot_max_shift();
    _stat_tool_moving_average_method();
    _stat_tool_negative_binomial_parameter();
    _stat_tool_multivariate_mixture();
    _stat_tool_distance_matrix();
    _stat_tool_vector_distance();
    _stat_tool_mixture();
    _stat_tool_chain_data();
    _stat_tool_discrete_parametric();
    _stat_tool_discrete_mixture();
    _stat_tool_dendrogram();
    _stat_tool_compound();
    _stat_tool_frequency_distribution();
    _stat_tool_regression();
    _stat_tool_convolution();
    _stat_tool_vectors();
    _stat_tool_compound_data();
    _stat_tool_forward();
    _stat_tool_multivariate_mixture_data();
    _stat_tool_clusters();
    _stat_tool_discrete_parametric_model();
    _stat_tool_discrete_distribution_data();
    _stat_tool_mixture_data();
    _stat_tool_convolution_data();
    _stat_tool_discrete_mixture_data();
}