#include <boost/python.hpp>
#include <stat_tool/stat_label.h>

void _stat_tool_stat_tool_key_word()
{
        std::string stat_tool_0cdd446515295e8e8373e99f328c3748_name = boost::python::extract< std::string >(boost::python::scope().attr("__name__") + ".stat_tool");
        boost::python::object stat_tool_0cdd446515295e8e8373e99f328c3748_module(boost::python::handle<  >(boost::python::borrowed(PyImport_AddModule(stat_tool_0cdd446515295e8e8373e99f328c3748_name.c_str()))));
        boost::python::scope().attr("stat_tool") = stat_tool_0cdd446515295e8e8373e99f328c3748_module;
        boost::python::scope stat_tool_0cdd446515295e8e8373e99f328c3748_scope = stat_tool_0cdd446515295e8e8373e99f328c3748_module;
        boost::python::enum_< enum ::stat_tool::stat_tool_key_word >("stat_tool_key_word")
            .value("STATW_INF_BOUND", ::stat_tool::stat_tool_key_word::STATW_INF_BOUND)
            .value("STATW_SUP_BOUND", ::stat_tool::stat_tool_key_word::STATW_SUP_BOUND)
            .value("STATW_PARAMETER", ::stat_tool::stat_tool_key_word::STATW_PARAMETER)
            .value("STATW_PROBABILITY", ::stat_tool::stat_tool_key_word::STATW_PROBABILITY)
            .value("STATW_SHAPE", ::stat_tool::stat_tool_key_word::STATW_SHAPE)
            .value("STATW_SCALE", ::stat_tool::stat_tool_key_word::STATW_SCALE)
            .value("STATW_ZERO_PROBABILITY", ::stat_tool::stat_tool_key_word::STATW_ZERO_PROBABILITY)
            .value("STATW_MEAN", ::stat_tool::stat_tool_key_word::STATW_MEAN)
            .value("STATW_STANDARD_DEVIATION", ::stat_tool::stat_tool_key_word::STATW_STANDARD_DEVIATION)
            .value("STATW_MEAN_DIRECTION", ::stat_tool::stat_tool_key_word::STATW_MEAN_DIRECTION)
            .value("STATW_CONCENTRATION", ::stat_tool::stat_tool_key_word::STATW_CONCENTRATION)
            .value("STATW_INTERCEPT", ::stat_tool::stat_tool_key_word::STATW_INTERCEPT)
            .value("STATW_SLOPE", ::stat_tool::stat_tool_key_word::STATW_SLOPE)
            .value("STATW_MIXTURE", ::stat_tool::stat_tool_key_word::STATW_MIXTURE)
            .value("STATW_CONVOLUTION", ::stat_tool::stat_tool_key_word::STATW_CONVOLUTION)
            .value("STATW_DISTRIBUTIONS", ::stat_tool::stat_tool_key_word::STATW_DISTRIBUTIONS)
            .value("STATW_DISTRIBUTION", ::stat_tool::stat_tool_key_word::STATW_DISTRIBUTION)
            .value("STATW_WEIGHT", ::stat_tool::stat_tool_key_word::STATW_WEIGHT)
            .value("STATW_WEIGHTS", ::stat_tool::stat_tool_key_word::STATW_WEIGHTS)
            .value("STATW_COMPONENTS", ::stat_tool::stat_tool_key_word::STATW_COMPONENTS)
            .value("STATW_COMPONENT", ::stat_tool::stat_tool_key_word::STATW_COMPONENT)
            .value("STATW_COMPOUND", ::stat_tool::stat_tool_key_word::STATW_COMPOUND)
            .value("STATW_SUM", ::stat_tool::stat_tool_key_word::STATW_SUM)
            .value("STATW_ELEMENTARY", ::stat_tool::stat_tool_key_word::STATW_ELEMENTARY)
            .value("STATW_VARIABLE", ::stat_tool::stat_tool_key_word::STATW_VARIABLE)
            .value("STATW_VARIABLES", ::stat_tool::stat_tool_key_word::STATW_VARIABLES)
            .value("STATW_DISTANCE", ::stat_tool::stat_tool_key_word::STATW_DISTANCE)
            .value("STATW_CATEGORIES", ::stat_tool::stat_tool_key_word::STATW_CATEGORIES)
            .value("STATW_PERIOD", ::stat_tool::stat_tool_key_word::STATW_PERIOD)
            .value("STATW_STATES", ::stat_tool::stat_tool_key_word::STATW_STATES)
            .value("STATW_INITIAL_PROBABILITIES", ::stat_tool::stat_tool_key_word::STATW_INITIAL_PROBABILITIES)
            .value("STATW_TRANSITION_PROBABILITIES", ::stat_tool::stat_tool_key_word::STATW_TRANSITION_PROBABILITIES)
            .value("STATW_STATE", ::stat_tool::stat_tool_key_word::STATW_STATE)
            .value("STATW_FUNCTION", ::stat_tool::stat_tool_key_word::STATW_FUNCTION)
            .value("STATW_OUTPUT_PROCESS", ::stat_tool::stat_tool_key_word::STATW_OUTPUT_PROCESS)
            .value("STATW_OUTPUT_PROCESSES", ::stat_tool::stat_tool_key_word::STATW_OUTPUT_PROCESSES)
            .value("STATW_NONPARAMETRIC", ::stat_tool::stat_tool_key_word::STATW_NONPARAMETRIC)
            .value("STATW_CATEGORICAL", ::stat_tool::stat_tool_key_word::STATW_CATEGORICAL)
            .value("STATW_PARAMETRIC", ::stat_tool::stat_tool_key_word::STATW_PARAMETRIC)
            .value("STATW_DISCRETE_PARAMETRIC", ::stat_tool::stat_tool_key_word::STATW_DISCRETE_PARAMETRIC)
            .value("STATW_CONTINUOUS_PARAMETRIC", ::stat_tool::stat_tool_key_word::STATW_CONTINUOUS_PARAMETRIC)
            .value("STATW_OBSERVATION_DISTRIBUTION", ::stat_tool::stat_tool_key_word::STATW_OBSERVATION_DISTRIBUTION)
            .value("STATW_OBSERVATION_MODEL", ::stat_tool::stat_tool_key_word::STATW_OBSERVATION_MODEL)
            .value("STATW_OBSERVATION_PROBABILITIES", ::stat_tool::stat_tool_key_word::STATW_OBSERVATION_PROBABILITIES)
            .value("STATW_OUTPUT", ::stat_tool::stat_tool_key_word::STATW_OUTPUT);
}