#include <boost/python.hpp>
#include <stat_tool/stat_tools.h>

void _std_vector_c12ae15f998e5bfbab2ce7e6d139e0e2()
{
        std::string std_a5e4e9231d6351ccb0e06756b389f0af_name = boost::python::extract< std::string >(boost::python::scope().attr("__name__") + ".std");
        boost::python::object std_a5e4e9231d6351ccb0e06756b389f0af_module(boost::python::handle<  >(boost::python::borrowed(PyImport_AddModule(std_a5e4e9231d6351ccb0e06756b389f0af_name.c_str()))));
        boost::python::scope().attr("std") = std_a5e4e9231d6351ccb0e06756b389f0af_module;
        boost::python::scope std_a5e4e9231d6351ccb0e06756b389f0af_scope = std_a5e4e9231d6351ccb0e06756b389f0af_module;
        void (::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::*method_pointer_51751263c203522f835af72eb99a19e1)(unsigned long, struct ::std::pair<std::pair<float, float>, std::basic_string<char> > const &) = &::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::assign;
        void (::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::*method_pointer_eee172dd387c52e2936e61292a8413cd)(class ::std::initializer_list<std::pair<std::pair<float, float>, std::basic_string<char> > >) = &::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::assign;
        class ::__gnu_cxx::__normal_iterator<std::pair<std::pair<float, float>, std::basic_string<char> > *, std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > > > (::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::*method_pointer_5f9f3d0d7bb15c2da5dae8218680f9f5)() = &::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::begin;
        class ::__gnu_cxx::__normal_iterator<std::pair<std::pair<float, float>, std::basic_string<char> > *, std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > > > (::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::*method_pointer_127fb02ac9815e25a2b7d7161fc8477c)() = &::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::end;
        class ::__gnu_cxx::__normal_iterator<const std::pair<std::pair<float, float>, std::basic_string<char> > *, std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > > > (::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::*method_pointer_24178d38e9ee50b0963504e09caeb00b)() const = &::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::end;
        class ::std::reverse_iterator<__gnu_cxx::__normal_iterator<std::pair<std::pair<float, float>, std::basic_string<char> > *, std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > > > > (::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::*method_pointer_076b46a01deb5097a78eaf53472654e9)() = &::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::rbegin;
        class ::std::reverse_iterator<__gnu_cxx::__normal_iterator<const std::pair<std::pair<float, float>, std::basic_string<char> > *, std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > > > > (::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::*method_pointer_654ef65ca50b5b2982f22da9543d5540)() const = &::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::rbegin;
        class ::std::reverse_iterator<__gnu_cxx::__normal_iterator<std::pair<std::pair<float, float>, std::basic_string<char> > *, std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > > > > (::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::*method_pointer_5b889076b4885704a5a7d467e78fdc6b)() = &::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::rend;
        class ::std::reverse_iterator<__gnu_cxx::__normal_iterator<const std::pair<std::pair<float, float>, std::basic_string<char> > *, std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > > > > (::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::*method_pointer_ffffa87d85c859e0a9de2d984d35c970)() const = &::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::rend;
        class ::__gnu_cxx::__normal_iterator<const std::pair<std::pair<float, float>, std::basic_string<char> > *, std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > > > (::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::*method_pointer_81c5882bf73a53a6817d1ba7742e8c61)() const = &::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::cbegin;
        class ::std::reverse_iterator<__gnu_cxx::__normal_iterator<const std::pair<std::pair<float, float>, std::basic_string<char> > *, std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > > > > (::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::*method_pointer_e62cdd8d740351e0849baa72c529675a)() const = &::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::crbegin;
        class ::std::reverse_iterator<__gnu_cxx::__normal_iterator<const std::pair<std::pair<float, float>, std::basic_string<char> > *, std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > > > > (::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::*method_pointer_8d45b2e7ebea5e9a9a802f5e5d79097a)() const = &::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::crend;
        unsigned long (::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::*method_pointer_1d65a388b2985e1faf32d82fc14d5a73)() const = &::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::size;
        unsigned long (::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::*method_pointer_aa4f7e06feaa53ac8e8aa9f22257baaf)() const = &::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::max_size;
        void (::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::*method_pointer_acb4c407577954c3a6004848f6c64d56)(unsigned long) = &::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::resize;
        void (::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::*method_pointer_1c662525c3bf50a8b61a6e9e7ead13b1)(unsigned long, struct ::std::pair<std::pair<float, float>, std::basic_string<char> > const &) = &::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::resize;
        void (::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::*method_pointer_fa61f57e195654dfa85a138b02318721)() = &::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::shrink_to_fit;
        unsigned long (::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::*method_pointer_01b292bf5eb4511796f2fddfa7288cd0)() const = &::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::capacity;
        bool (::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::*method_pointer_ec7f09d206975c7e90d1547afe2aee67)() const = &::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::empty;
        void (::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::*method_pointer_2452b504d2df5dd68873f97ef9187ff9)(unsigned long) = &::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::reserve;
        struct ::std::pair<std::pair<float, float>, std::basic_string<char> > & (::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::*method_pointer_57987b9af87c598490741033675d8742)(unsigned long) = &::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::operator[];
        struct ::std::pair<std::pair<float, float>, std::basic_string<char> > const & (::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::*method_pointer_383563f5544b517eb7d1720c73733d76)(unsigned long) const = &::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::operator[];
        struct ::std::pair<std::pair<float, float>, std::basic_string<char> > & (::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::*method_pointer_8f40239f2d3d589c9887ceebe5e02cbd)(unsigned long) = &::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::at;
        struct ::std::pair<std::pair<float, float>, std::basic_string<char> > const & (::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::*method_pointer_0349eb08960650b58f9423bbe63a4af8)(unsigned long) const = &::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::at;
        struct ::std::pair<std::pair<float, float>, std::basic_string<char> > & (::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::*method_pointer_e0b8b70900185172814f9e4600dedf07)() = &::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::front;
        struct ::std::pair<std::pair<float, float>, std::basic_string<char> > const & (::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::*method_pointer_fc2d6a131a61538093dd66347beb30c9)() const = &::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::front;
        struct ::std::pair<std::pair<float, float>, std::basic_string<char> > & (::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::*method_pointer_f2ae3d2bec4c5154b2f76f8ad39ca44b)() = &::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::back;
        struct ::std::pair<std::pair<float, float>, std::basic_string<char> > const & (::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::*method_pointer_fbdf71ee65855d79bbc282aff5c5e17d)() const = &::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::back;
        struct ::std::pair<std::pair<float, float>, std::basic_string<char> > * (::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::*method_pointer_45b6fa64576059d2a536af408ca7165b)() = &::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::data;
        struct ::std::pair<std::pair<float, float>, std::basic_string<char> > const * (::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::*method_pointer_cffa6d4d5af25a6bb98a09dbd1606ba2)() const = &::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::data;
        void (::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::*method_pointer_481e8bb6d5515600aadfd58ba15d8808)(struct ::std::pair<std::pair<float, float>, std::basic_string<char> > const &) = &::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::push_back;
        void (::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::*method_pointer_a89eb66ff684500ab5b87ecb307a2bea)() = &::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::pop_back;
        class ::__gnu_cxx::__normal_iterator<std::pair<std::pair<float, float>, std::basic_string<char> > *, std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > > > (::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::*method_pointer_92e8ba7fbe75598b9399d8374f22d0e1)(class ::__gnu_cxx::__normal_iterator<const std::pair<std::pair<float, float>, std::basic_string<char> > *, std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > > >, unsigned long, struct ::std::pair<std::pair<float, float>, std::basic_string<char> > const &) = &::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::insert;
        class ::__gnu_cxx::__normal_iterator<std::pair<std::pair<float, float>, std::basic_string<char> > *, std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > > > (::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::*method_pointer_9b623879ab615a9db0d0da23816eb969)(class ::__gnu_cxx::__normal_iterator<const std::pair<std::pair<float, float>, std::basic_string<char> > *, std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > > >) = &::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::erase;
        class ::__gnu_cxx::__normal_iterator<std::pair<std::pair<float, float>, std::basic_string<char> > *, std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > > > (::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::*method_pointer_feddd31feeb45fddaf22a464783cc815)(class ::__gnu_cxx::__normal_iterator<const std::pair<std::pair<float, float>, std::basic_string<char> > *, std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > > >, class ::__gnu_cxx::__normal_iterator<const std::pair<std::pair<float, float>, std::basic_string<char> > *, std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > > >) = &::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::erase;
        void (::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::*method_pointer_04722e1adfbf59be91eb120a160d5094)(class ::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > > &) = &::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::swap;
        void (::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::*method_pointer_a3ee52903a4d57e5ba91ddab87512076)() = &::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >::clear;
        boost::python::class_< class ::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > >, std::shared_ptr< class ::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > > > >("_Vector_c12ae15f998e5bfbab2ce7e6d139e0e2", boost::python::no_init)
            .def(boost::python::init<  >())
            .def(boost::python::init< class ::std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > const & >())
            .def(boost::python::init< unsigned long, class ::std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > const & >())
            .def(boost::python::init< unsigned long, struct ::std::pair<std::pair<float, float>, std::basic_string<char> > const &, class ::std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > const & >())
            .def(boost::python::init< class ::std::vector<std::pair<std::pair<float, float>, std::basic_string<char> >, std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > > const & >())
            .def(boost::python::init< class ::std::initializer_list<std::pair<std::pair<float, float>, std::basic_string<char> > >, class ::std::allocator<std::pair<std::pair<float, float>, std::basic_string<char> > > const & >())
            .def("assign", method_pointer_51751263c203522f835af72eb99a19e1)
            .def("assign", method_pointer_eee172dd387c52e2936e61292a8413cd)
            .def("begin", method_pointer_5f9f3d0d7bb15c2da5dae8218680f9f5)
            .def("end", method_pointer_127fb02ac9815e25a2b7d7161fc8477c)
            .def("end", method_pointer_24178d38e9ee50b0963504e09caeb00b)
            .def("rbegin", method_pointer_076b46a01deb5097a78eaf53472654e9)
            .def("rbegin", method_pointer_654ef65ca50b5b2982f22da9543d5540)
            .def("rend", method_pointer_5b889076b4885704a5a7d467e78fdc6b)
            .def("rend", method_pointer_ffffa87d85c859e0a9de2d984d35c970)
            .def("cbegin", method_pointer_81c5882bf73a53a6817d1ba7742e8c61)
            .def("crbegin", method_pointer_e62cdd8d740351e0849baa72c529675a)
            .def("crend", method_pointer_8d45b2e7ebea5e9a9a802f5e5d79097a)
            .def("size", method_pointer_1d65a388b2985e1faf32d82fc14d5a73)
            .def("max_size", method_pointer_aa4f7e06feaa53ac8e8aa9f22257baaf)
            .def("resize", method_pointer_acb4c407577954c3a6004848f6c64d56)
            .def("resize", method_pointer_1c662525c3bf50a8b61a6e9e7ead13b1)
            .def("shrink_to_fit", method_pointer_fa61f57e195654dfa85a138b02318721)
            .def("capacity", method_pointer_01b292bf5eb4511796f2fddfa7288cd0)
            .def("empty", method_pointer_ec7f09d206975c7e90d1547afe2aee67)
            .def("reserve", method_pointer_2452b504d2df5dd68873f97ef9187ff9)
            .def("__setitem__", method_pointer_57987b9af87c598490741033675d8742, boost::python::return_internal_reference<>())
            .def("__getitem__", method_pointer_383563f5544b517eb7d1720c73733d76, boost::python::return_value_policy< boost::python::return_by_value >())
            .def("at", method_pointer_8f40239f2d3d589c9887ceebe5e02cbd, boost::python::return_internal_reference<>())
            .def("at", method_pointer_0349eb08960650b58f9423bbe63a4af8, boost::python::return_value_policy< boost::python::return_by_value >())
            .def("front", method_pointer_e0b8b70900185172814f9e4600dedf07, boost::python::return_internal_reference<>())
            .def("front", method_pointer_fc2d6a131a61538093dd66347beb30c9, boost::python::return_value_policy< boost::python::return_by_value >())
            .def("back", method_pointer_f2ae3d2bec4c5154b2f76f8ad39ca44b, boost::python::return_internal_reference<>())
            .def("back", method_pointer_fbdf71ee65855d79bbc282aff5c5e17d, boost::python::return_value_policy< boost::python::return_by_value >())
            .def("data", method_pointer_45b6fa64576059d2a536af408ca7165b, boost::python::return_value_policy< boost::python::reference_existing_object >())
            .def("data", method_pointer_cffa6d4d5af25a6bb98a09dbd1606ba2, boost::python::return_value_policy< boost::python::reference_existing_object >())
            .def("push_back", method_pointer_481e8bb6d5515600aadfd58ba15d8808)
            .def("pop_back", method_pointer_a89eb66ff684500ab5b87ecb307a2bea)
            .def("insert", method_pointer_92e8ba7fbe75598b9399d8374f22d0e1)
            .def("erase", method_pointer_9b623879ab615a9db0d0da23816eb969)
            .def("erase", method_pointer_feddd31feeb45fddaf22a464783cc815)
            .def("swap", method_pointer_04722e1adfbf59be91eb120a160d5094)
            .def("clear", method_pointer_a3ee52903a4d57e5ba91ddab87512076);
}