#include <boost/python.hpp>
#include <stat_tool/stat_tools.h>

void _std_vector_81e75b7398665005aad6590cb36f8edf()
{
        std::string std_a5e4e9231d6351ccb0e06756b389f0af_name = boost::python::extract< std::string >(boost::python::scope().attr("__name__") + ".std");
        boost::python::object std_a5e4e9231d6351ccb0e06756b389f0af_module(boost::python::handle<  >(boost::python::borrowed(PyImport_AddModule(std_a5e4e9231d6351ccb0e06756b389f0af_name.c_str()))));
        boost::python::scope().attr("std") = std_a5e4e9231d6351ccb0e06756b389f0af_module;
        boost::python::scope std_a5e4e9231d6351ccb0e06756b389f0af_scope = std_a5e4e9231d6351ccb0e06756b389f0af_module;
        void (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_00103e3a3cc45f39a7289cddeb40e880)(unsigned long, struct ::boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > const &) = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::assign;
        void (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_99f57cfcc3c957c5bfb14991f0da5b27)(class ::std::initializer_list<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > >) = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::assign;
        class ::__gnu_cxx::__normal_iterator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > *, std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > > > (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_40af892db0a15849850cb4c08e01c411)() = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::begin;
        class ::__gnu_cxx::__normal_iterator<const boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > *, std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > > > (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_b3e8a5b574bb59f8af8df4bada30cec9)() const = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::begin;
        class ::__gnu_cxx::__normal_iterator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > *, std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > > > (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_1df311730edf50e29a32985364db76c2)() = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::end;
        class ::__gnu_cxx::__normal_iterator<const boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > *, std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > > > (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_593ca6eb25ea524d87e4e532163195f7)() const = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::end;
        class ::std::reverse_iterator<__gnu_cxx::__normal_iterator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > *, std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > > > > (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_b6dc2d765b45596e9e97afc1c7da2c00)() = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::rbegin;
        class ::std::reverse_iterator<__gnu_cxx::__normal_iterator<const boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > *, std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > > > > (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_b434985bc4185e69a7209a0977f023c5)() const = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::rbegin;
        class ::std::reverse_iterator<__gnu_cxx::__normal_iterator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > *, std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > > > > (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_49a817bd9a2f5b4290063e5eb071af6a)() = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::rend;
        class ::std::reverse_iterator<__gnu_cxx::__normal_iterator<const boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > *, std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > > > > (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_8b842466a18c58b1a7131cbf4f015f48)() const = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::rend;
        class ::__gnu_cxx::__normal_iterator<const boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > *, std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > > > (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_3dc940ab0f185a2d8f116e3fc4de949b)() const = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::cbegin;
        class ::__gnu_cxx::__normal_iterator<const boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > *, std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > > > (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_b4f68b254bed5c878027974edb894873)() const = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::cend;
        class ::std::reverse_iterator<__gnu_cxx::__normal_iterator<const boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > *, std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > > > > (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_b77efcb3779a596bbe8f55a19780d87b)() const = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::crbegin;
        class ::std::reverse_iterator<__gnu_cxx::__normal_iterator<const boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > *, std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > > > > (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_96e01ebfaf9f5cad8386cf50f2818d64)() const = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::crend;
        unsigned long (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_108b659b34c35231a08a6752262d80ba)() const = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::size;
        unsigned long (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_3a7314dfd39958d6b9d4ae54721076fb)() const = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::max_size;
        void (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_64a4026019765181b1a4bcc15c40b663)(unsigned long) = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::resize;
        void (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_0d1f4083fc945737baf508e58b6a12f5)(unsigned long, struct ::boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > const &) = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::resize;
        void (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_2c1ae3a3e89c57a4ab1ed1fbef2dd638)() = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::shrink_to_fit;
        unsigned long (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_38ef854dc6b45880adddc5b6f84b0159)() const = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::capacity;
        bool (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_b1c6152271f456a1b87c9cded6fe91a8)() const = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::empty;
        void (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_d5c7118066a45d5e9441f623e8b39427)(unsigned long) = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::reserve;
        struct ::boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > & (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_5dbe06c6400c5d43b7d27991662a59fa)(unsigned long) = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::operator[];
        struct ::boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > const & (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_bf8c1e68ac60562da234e3f18b5f5d7f)(unsigned long) const = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::operator[];
        struct ::boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > & (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_b825063419e95b59be7270481aa05130)(unsigned long) = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::at;
        struct ::boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > const & (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_f29383b4880a5cc8a6e5a759907e533c)(unsigned long) const = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::at;
        struct ::boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > & (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_e3e561ec17d75a28aa03eaf42e2a50b5)() = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::front;
        struct ::boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > const & (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_22d9a6297b185467a398da6aba5c1f9c)() const = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::front;
        struct ::boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > & (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_47de5d0329a7523d92092b5c34ba568c)() = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::back;
        struct ::boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > const & (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_07becd62effc533dbe3f104fe82c3dc5)() const = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::back;
        struct ::boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > * (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_56a0ba7caeab54a7915033a5666cecfb)() = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::data;
        struct ::boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > const * (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_a4363aea7eaa5b2e91cef4ded4b9afc1)() const = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::data;
        void (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_f0518cbdc4385a6690110e5a0aa5d4b7)(struct ::boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > const &) = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::push_back;
        void (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_7db7f0eedde15a2e80cad566d5316b44)() = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::pop_back;
        class ::__gnu_cxx::__normal_iterator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > *, std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > > > (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_c3b30042c7595554980c87b78b836ae2)(class ::__gnu_cxx::__normal_iterator<const boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > *, std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > > >, struct ::boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > const &) = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::insert;
        class ::__gnu_cxx::__normal_iterator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > *, std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > > > (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_c85483811ad85a7e81ac48636432c8bf)(class ::__gnu_cxx::__normal_iterator<const boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > *, std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > > >, class ::std::initializer_list<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > >) = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::insert;
        class ::__gnu_cxx::__normal_iterator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > *, std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > > > (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_32c40f3d8f03565c834c7a7d9d96f8d8)(class ::__gnu_cxx::__normal_iterator<const boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > *, std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > > >, unsigned long, struct ::boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > const &) = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::insert;
        class ::__gnu_cxx::__normal_iterator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > *, std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > > > (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_bf72c433f7e9565eb044238ba0c8ad8d)(class ::__gnu_cxx::__normal_iterator<const boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > *, std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > > >) = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::erase;
        class ::__gnu_cxx::__normal_iterator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > *, std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > > > (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_e5e313cea38e5521a97465ac4e4884a3)(class ::__gnu_cxx::__normal_iterator<const boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > *, std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > > >, class ::__gnu_cxx::__normal_iterator<const boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > *, std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > > >) = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::erase;
        void (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_ae3d7a833d35533698fe77ebf39f1b44)(class ::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > > &) = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::swap;
        void (::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::*method_pointer_b3af0b5079b55ae8953cfb7de1abc879)() = &::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >::clear;
        boost::python::class_< class ::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >, std::shared_ptr< class ::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > > > >("_Vector_81e75b7398665005aad6590cb36f8edf", boost::python::no_init)
            .def(boost::python::init<  >())
            .def(boost::python::init< class ::std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > const & >())
            .def(boost::python::init< unsigned long, class ::std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > const & >())
            .def(boost::python::init< unsigned long, struct ::boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > const &, class ::std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > const & >())
            .def(boost::python::init< class ::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > > const & >())
            .def(boost::python::init< class ::std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > > const &, class ::std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > const & >())
            .def(boost::python::init< class ::std::initializer_list<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > >, class ::std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > const & >())
            .def("assign", method_pointer_00103e3a3cc45f39a7289cddeb40e880)
            .def("assign", method_pointer_99f57cfcc3c957c5bfb14991f0da5b27)
            .def("begin", method_pointer_40af892db0a15849850cb4c08e01c411)
            .def("begin", method_pointer_b3e8a5b574bb59f8af8df4bada30cec9)
            .def("end", method_pointer_1df311730edf50e29a32985364db76c2)
            .def("end", method_pointer_593ca6eb25ea524d87e4e532163195f7)
            .def("rbegin", method_pointer_b6dc2d765b45596e9e97afc1c7da2c00)
            .def("rbegin", method_pointer_b434985bc4185e69a7209a0977f023c5)
            .def("rend", method_pointer_49a817bd9a2f5b4290063e5eb071af6a)
            .def("rend", method_pointer_8b842466a18c58b1a7131cbf4f015f48)
            .def("cbegin", method_pointer_3dc940ab0f185a2d8f116e3fc4de949b)
            .def("cend", method_pointer_b4f68b254bed5c878027974edb894873)
            .def("crbegin", method_pointer_b77efcb3779a596bbe8f55a19780d87b)
            .def("crend", method_pointer_96e01ebfaf9f5cad8386cf50f2818d64)
            .def("size", method_pointer_108b659b34c35231a08a6752262d80ba)
            .def("max_size", method_pointer_3a7314dfd39958d6b9d4ae54721076fb)
            .def("resize", method_pointer_64a4026019765181b1a4bcc15c40b663)
            .def("resize", method_pointer_0d1f4083fc945737baf508e58b6a12f5)
            .def("shrink_to_fit", method_pointer_2c1ae3a3e89c57a4ab1ed1fbef2dd638)
            .def("capacity", method_pointer_38ef854dc6b45880adddc5b6f84b0159)
            .def("empty", method_pointer_b1c6152271f456a1b87c9cded6fe91a8)
            .def("reserve", method_pointer_d5c7118066a45d5e9441f623e8b39427)
            .def("__setitem__", method_pointer_5dbe06c6400c5d43b7d27991662a59fa, boost::python::return_internal_reference<>())
            .def("__getitem__", method_pointer_bf8c1e68ac60562da234e3f18b5f5d7f, boost::python::return_value_policy< boost::python::return_by_value >())
            .def("at", method_pointer_b825063419e95b59be7270481aa05130, boost::python::return_internal_reference<>())
            .def("at", method_pointer_f29383b4880a5cc8a6e5a759907e533c, boost::python::return_value_policy< boost::python::return_by_value >())
            .def("front", method_pointer_e3e561ec17d75a28aa03eaf42e2a50b5, boost::python::return_internal_reference<>())
            .def("front", method_pointer_22d9a6297b185467a398da6aba5c1f9c, boost::python::return_value_policy< boost::python::return_by_value >())
            .def("back", method_pointer_47de5d0329a7523d92092b5c34ba568c, boost::python::return_internal_reference<>())
            .def("back", method_pointer_07becd62effc533dbe3f104fe82c3dc5, boost::python::return_value_policy< boost::python::return_by_value >())
            .def("data", method_pointer_56a0ba7caeab54a7915033a5666cecfb, boost::python::return_value_policy< boost::python::reference_existing_object >())
            .def("data", method_pointer_a4363aea7eaa5b2e91cef4ded4b9afc1, boost::python::return_value_policy< boost::python::reference_existing_object >())
            .def("push_back", method_pointer_f0518cbdc4385a6690110e5a0aa5d4b7)
            .def("pop_back", method_pointer_7db7f0eedde15a2e80cad566d5316b44)
            .def("insert", method_pointer_c3b30042c7595554980c87b78b836ae2)
            .def("insert", method_pointer_c85483811ad85a7e81ac48636432c8bf)
            .def("insert", method_pointer_32c40f3d8f03565c834c7a7d9d96f8d8)
            .def("erase", method_pointer_bf72c433f7e9565eb044238ba0c8ad8d)
            .def("erase", method_pointer_e5e313cea38e5521a97465ac4e4884a3)
            .def("swap", method_pointer_ae3d7a833d35533698fe77ebf39f1b44)
            .def("clear", method_pointer_b3af0b5079b55ae8953cfb7de1abc879);
}