# -*-python-*-
 	

import os
pj = os.path.join
Import("env")

env.EnableQt4Modules(['QtCore','QtOpenGL', 'QtGui'])
# Export symbols under windows
if env['compiler'] == 'mingw':
    LINKFLAGS=["-enable-stdcall-fixup",
               "-enable-auto-import",
               "-enable-runtime-pseudo-reloc",
               "-s"]
    env.AppendUnique(LINKFLAGS=LINKFLAGS)

# Build wrappers as shared libraries
includes= env.ALEAGlob('*.h')
sources = env.ALEAGlob('*.cpp')

LIBS = ['vptool', 'vpstat_tool']
env.AppendUnique(LIBS=LIBS)

# Add defines to export symbols on Windows
env.AppendUnique(CPPDEFINES=['MESSAGE'])
env.AppendUnique(LIBS=['vptool', 'vpstat_tool'])

#sources.remove(pj(".","cstat_tool.cpp"))
#env.ALEAWrapper("../openalea/stat_tool/old", "cstat_tool", ["cstat_tool.cpp"])


env.ALEAWrapper("../stat_tool", "_stat_tool", sources)
# includes in wrappers should be restricted to boost_python_aliases.h and wrapper_util.h
# inc = env.Install('$build_includedir/stat_tool', includes) 
inc = env.Install('$build_includedir/stat_tool', ["boost_python_aliases.h", "wrapper_util.h"])
env.Alias('build', inc)

