# -*-python-*-

import os
pj = os.path.join
Import("env")

#env.EnableQt4Modules(['QtCore','QtOpenGL', 'QtGui'])
# Export symbols under windows
if env['compiler'] == 'mingw':
    LINKFLAGS=["-enable-stdcall-fixup",
               "-enable-auto-import",
               "-enable-runtime-pseudo-reloc",
               "-s"]
    env.AppendUnique(LINKFLAGS=LINKFLAGS)
# Build wrappers as shared libraries
includes= env.ALEAGlob('*.h')
sources = env.ALEAGlob('*.cpp')

#LIBS = ['vptool', 'vpstat_tool']
LIBS = ['vpstat_tool']
env.AppendUnique(LIBS=LIBS)

# Add defines to export symbols on Windows
env.AppendUnique(CPPDEFINES=['MESSAGE'])

env.ALEAWrapper("../openalea/stat_tool", "_stat_tool", sources)
