# -*-python-*-


import os
pj = os.path.join
Import("env")

# Export symbols under windows
if env['compiler'] == 'mingw':
    LINKFLAGS=["-enable-stdcall-fixup",
               "-enable-auto-import",
               "-enable-runtime-pseudo-reloc",
               "-s"]
    env.AppendUnique(LINKFLAGS=LINKFLAGS)

# Build wrappers as shared libraries
includes= env.ALEAGlob('*.h')
sources = env.ALEAGlob('*.cpp')

#LIBS = ['vptool', 'vpstat_tool']
LIBS = ['vpstat_tool']
env.AppendUnique(LIBS=LIBS)

# Add defines to export symbols on Windows
env.AppendUnique(CPPDEFINES=['MESSAGE'])



env.ALEAWrapper("../stat_tool", "__stat_tool", sources)
# includes in wrappers should be restricted to boost_python_aliases.h and wrapper_util.h
# inc = env.Install('$build_includedir/stat_tool', includes)
# inc = env.Install('$build_includedir/stat_tool', ["boost_python_aliases.h", "wrapper_util.h"])
# env.Alias('build', inc)

