#include "_stat_tool.h"



namespace autowig
{

    void method_decorator_e6878cf55d2f535eb8436b1bcc3b0cb5(class ::std::move_iterator< class ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, class ::std::vector< enum ::stat_tool::discrete_parametric, class ::std::allocator< enum ::stat_tool::discrete_parametric > > > > & instance, const class ::std::move_iterator< class ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, class ::std::vector< enum ::stat_tool::discrete_parametric, class ::std::allocator< enum ::stat_tool::discrete_parametric > > > > & param_out) { instance.operator++() = param_out; }
    void method_decorator_447a50d87d5859128224333bcad69e98(class ::std::move_iterator< class ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, class ::std::vector< enum ::stat_tool::discrete_parametric, class ::std::allocator< enum ::stat_tool::discrete_parametric > > > > & instance, const class ::std::move_iterator< class ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, class ::std::vector< enum ::stat_tool::discrete_parametric, class ::std::allocator< enum ::stat_tool::discrete_parametric > > > > & param_out) { instance.operator--() = param_out; }
    void method_decorator_c8df55aae77d5cbd8ef7125b677f96e6(class ::std::move_iterator< class ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, class ::std::vector< enum ::stat_tool::discrete_parametric, class ::std::allocator< enum ::stat_tool::discrete_parametric > > > > & instance, ::std::move_iterator< class ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, class ::std::vector< enum ::stat_tool::discrete_parametric, class ::std::allocator< enum ::stat_tool::discrete_parametric > > > >::difference_type  param_in_0, const class ::std::move_iterator< class ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, class ::std::vector< enum ::stat_tool::discrete_parametric, class ::std::allocator< enum ::stat_tool::discrete_parametric > > > > & param_out) { instance.operator+=(param_in_0) = param_out; }
    void method_decorator_95704bf236c659f28b4177235cffb95c(class ::std::move_iterator< class ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, class ::std::vector< enum ::stat_tool::discrete_parametric, class ::std::allocator< enum ::stat_tool::discrete_parametric > > > > & instance, ::std::move_iterator< class ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, class ::std::vector< enum ::stat_tool::discrete_parametric, class ::std::allocator< enum ::stat_tool::discrete_parametric > > > >::difference_type  param_in_0, const class ::std::move_iterator< class ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, class ::std::vector< enum ::stat_tool::discrete_parametric, class ::std::allocator< enum ::stat_tool::discrete_parametric > > > > & param_out) { instance.operator-=(param_in_0) = param_out; }
}

#if defined(_MSC_VER)
    #if (_MSC_VER == 1900)
namespace boost
{
    template <> class ::std::move_iterator< class ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, class ::std::vector< enum ::stat_tool::discrete_parametric, class ::std::allocator< enum ::stat_tool::discrete_parametric > > > > const volatile * get_pointer<class ::std::move_iterator< class ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, class ::std::vector< enum ::stat_tool::discrete_parametric, class ::std::allocator< enum ::stat_tool::discrete_parametric > > > > const volatile >(class ::std::move_iterator< class ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, class ::std::vector< enum ::stat_tool::discrete_parametric, class ::std::allocator< enum ::stat_tool::discrete_parametric > > > > const volatile *c) { return c; }
}
    #endif
#endif



void wrapper_f38d1184226e5eab899f2ead9c835dc3()
{

    std::string name_a5e4e9231d6351ccb0e06756b389f0af = boost::python::extract< std::string >(boost::python::scope().attr("__name__") + ".std");
    boost::python::object module_a5e4e9231d6351ccb0e06756b389f0af(boost::python::handle<  >(boost::python::borrowed(PyImport_AddModule(name_a5e4e9231d6351ccb0e06756b389f0af.c_str()))));
    boost::python::scope().attr("std") = module_a5e4e9231d6351ccb0e06756b389f0af;
    boost::python::scope scope_a5e4e9231d6351ccb0e06756b389f0af = module_a5e4e9231d6351ccb0e06756b389f0af;
    class ::std::move_iterator< class ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, class ::std::vector< enum ::stat_tool::discrete_parametric, class ::std::allocator< enum ::stat_tool::discrete_parametric > > > > & (::std::move_iterator< ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, ::std::vector< enum ::stat_tool::discrete_parametric, ::std::allocator< enum ::stat_tool::discrete_parametric > > > >::*method_pointer_e6878cf55d2f535eb8436b1bcc3b0cb5)() = &::std::move_iterator< class ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, class ::std::vector< enum ::stat_tool::discrete_parametric, class ::std::allocator< enum ::stat_tool::discrete_parametric > > > >::operator++;
    class ::std::move_iterator< class ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, class ::std::vector< enum ::stat_tool::discrete_parametric, class ::std::allocator< enum ::stat_tool::discrete_parametric > > > >  (::std::move_iterator< ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, ::std::vector< enum ::stat_tool::discrete_parametric, ::std::allocator< enum ::stat_tool::discrete_parametric > > > >::*method_pointer_031c59f1989e5e0580e63c60f555b3d6)(int ) = &::std::move_iterator< class ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, class ::std::vector< enum ::stat_tool::discrete_parametric, class ::std::allocator< enum ::stat_tool::discrete_parametric > > > >::operator++;
    class ::std::move_iterator< class ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, class ::std::vector< enum ::stat_tool::discrete_parametric, class ::std::allocator< enum ::stat_tool::discrete_parametric > > > > & (::std::move_iterator< ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, ::std::vector< enum ::stat_tool::discrete_parametric, ::std::allocator< enum ::stat_tool::discrete_parametric > > > >::*method_pointer_447a50d87d5859128224333bcad69e98)() = &::std::move_iterator< class ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, class ::std::vector< enum ::stat_tool::discrete_parametric, class ::std::allocator< enum ::stat_tool::discrete_parametric > > > >::operator--;
    class ::std::move_iterator< class ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, class ::std::vector< enum ::stat_tool::discrete_parametric, class ::std::allocator< enum ::stat_tool::discrete_parametric > > > >  (::std::move_iterator< ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, ::std::vector< enum ::stat_tool::discrete_parametric, ::std::allocator< enum ::stat_tool::discrete_parametric > > > >::*method_pointer_2f6e92cbd739536caacb4e0d16247e80)(int ) = &::std::move_iterator< class ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, class ::std::vector< enum ::stat_tool::discrete_parametric, class ::std::allocator< enum ::stat_tool::discrete_parametric > > > >::operator--;
    class ::std::move_iterator< class ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, class ::std::vector< enum ::stat_tool::discrete_parametric, class ::std::allocator< enum ::stat_tool::discrete_parametric > > > >  (::std::move_iterator< ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, ::std::vector< enum ::stat_tool::discrete_parametric, ::std::allocator< enum ::stat_tool::discrete_parametric > > > >::*method_pointer_f12062e32c6c5379bdf520dd359f79cb)(::std::move_iterator< class ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, class ::std::vector< enum ::stat_tool::discrete_parametric, class ::std::allocator< enum ::stat_tool::discrete_parametric > > > >::difference_type ) const = &::std::move_iterator< class ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, class ::std::vector< enum ::stat_tool::discrete_parametric, class ::std::allocator< enum ::stat_tool::discrete_parametric > > > >::operator+;
    class ::std::move_iterator< class ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, class ::std::vector< enum ::stat_tool::discrete_parametric, class ::std::allocator< enum ::stat_tool::discrete_parametric > > > > & (::std::move_iterator< ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, ::std::vector< enum ::stat_tool::discrete_parametric, ::std::allocator< enum ::stat_tool::discrete_parametric > > > >::*method_pointer_c8df55aae77d5cbd8ef7125b677f96e6)(::std::move_iterator< class ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, class ::std::vector< enum ::stat_tool::discrete_parametric, class ::std::allocator< enum ::stat_tool::discrete_parametric > > > >::difference_type ) = &::std::move_iterator< class ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, class ::std::vector< enum ::stat_tool::discrete_parametric, class ::std::allocator< enum ::stat_tool::discrete_parametric > > > >::operator+=;
    class ::std::move_iterator< class ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, class ::std::vector< enum ::stat_tool::discrete_parametric, class ::std::allocator< enum ::stat_tool::discrete_parametric > > > >  (::std::move_iterator< ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, ::std::vector< enum ::stat_tool::discrete_parametric, ::std::allocator< enum ::stat_tool::discrete_parametric > > > >::*method_pointer_af9d4df507bd55eb8e61006096f4d312)(::std::move_iterator< class ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, class ::std::vector< enum ::stat_tool::discrete_parametric, class ::std::allocator< enum ::stat_tool::discrete_parametric > > > >::difference_type ) const = &::std::move_iterator< class ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, class ::std::vector< enum ::stat_tool::discrete_parametric, class ::std::allocator< enum ::stat_tool::discrete_parametric > > > >::operator-;
    class ::std::move_iterator< class ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, class ::std::vector< enum ::stat_tool::discrete_parametric, class ::std::allocator< enum ::stat_tool::discrete_parametric > > > > & (::std::move_iterator< ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, ::std::vector< enum ::stat_tool::discrete_parametric, ::std::allocator< enum ::stat_tool::discrete_parametric > > > >::*method_pointer_95704bf236c659f28b4177235cffb95c)(::std::move_iterator< class ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, class ::std::vector< enum ::stat_tool::discrete_parametric, class ::std::allocator< enum ::stat_tool::discrete_parametric > > > >::difference_type ) = &::std::move_iterator< class ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, class ::std::vector< enum ::stat_tool::discrete_parametric, class ::std::allocator< enum ::stat_tool::discrete_parametric > > > >::operator-=;
    boost::python::class_< class ::std::move_iterator< class ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, class ::std::vector< enum ::stat_tool::discrete_parametric, class ::std::allocator< enum ::stat_tool::discrete_parametric > > > >, autowig::Held< class ::std::move_iterator< class ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, class ::std::vector< enum ::stat_tool::discrete_parametric, class ::std::allocator< enum ::stat_tool::discrete_parametric > > > > >::Type > class_f38d1184226e5eab899f2ead9c835dc3("_MoveIterator_f38d1184226e5eab899f2ead9c835dc3", "", boost::python::no_init);
    class_f38d1184226e5eab899f2ead9c835dc3.def(boost::python::init<  >(""));
    class_f38d1184226e5eab899f2ead9c835dc3.def(boost::python::init< class ::std::move_iterator< class ::__gnu_cxx::__normal_iterator< enum ::stat_tool::discrete_parametric *, class ::std::vector< enum ::stat_tool::discrete_parametric, class ::std::allocator< enum ::stat_tool::discrete_parametric > > > > const & >(""));
    class_f38d1184226e5eab899f2ead9c835dc3.def("__next__", method_pointer_e6878cf55d2f535eb8436b1bcc3b0cb5, boost::python::return_internal_reference<>(), "");
    class_f38d1184226e5eab899f2ead9c835dc3.def("__next__", autowig::method_decorator_e6878cf55d2f535eb8436b1bcc3b0cb5);
    class_f38d1184226e5eab899f2ead9c835dc3.def("__next__", method_pointer_031c59f1989e5e0580e63c60f555b3d6, "");
    class_f38d1184226e5eab899f2ead9c835dc3.def("__prev__", method_pointer_447a50d87d5859128224333bcad69e98, boost::python::return_internal_reference<>(), "");
    class_f38d1184226e5eab899f2ead9c835dc3.def("__prev__", autowig::method_decorator_447a50d87d5859128224333bcad69e98);
    class_f38d1184226e5eab899f2ead9c835dc3.def("__prev__", method_pointer_2f6e92cbd739536caacb4e0d16247e80, "");
    class_f38d1184226e5eab899f2ead9c835dc3.def("__add__", method_pointer_f12062e32c6c5379bdf520dd359f79cb, "");
    class_f38d1184226e5eab899f2ead9c835dc3.def("__iadd__", method_pointer_c8df55aae77d5cbd8ef7125b677f96e6, boost::python::return_internal_reference<>(), "");
    class_f38d1184226e5eab899f2ead9c835dc3.def("__iadd__", autowig::method_decorator_c8df55aae77d5cbd8ef7125b677f96e6);
    class_f38d1184226e5eab899f2ead9c835dc3.def("__sub__", method_pointer_af9d4df507bd55eb8e61006096f4d312, "");
    class_f38d1184226e5eab899f2ead9c835dc3.def("__isub__", method_pointer_95704bf236c659f28b4177235cffb95c, boost::python::return_internal_reference<>(), "");
    class_f38d1184226e5eab899f2ead9c835dc3.def("__isub__", autowig::method_decorator_95704bf236c659f28b4177235cffb95c);

}