#include "_stat_tool.h"



namespace autowig
{

    void method_decorator_5c2439bfc6cc537ab09bd5c61e98ccac(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & instance, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_0, const ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::reference  param_out)     { instance.operator[](param_in_0) = param_out; }
    void method_decorator_2b1847ed6305532081540fcee3a3039e(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & instance, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_0, const ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::reference  param_out)     { instance.at(param_in_0) = param_out; }
    void method_decorator_492d67ed747f57fa96bdcfb12ff2b092(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & instance, const ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::reference  param_out)     { instance.front() = param_out; }
    void method_decorator_eaac392eb32d523c9067d99099468947(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & instance, const ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::reference  param_out)     { instance.back() = param_out; }
    void method_decorator_a41aa0fc6fb85a67b1ff7065e002ce8a(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & instance, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const & param_in_0, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & param_out)     { instance.operator+=(param_in_0) = param_out; }
    void method_decorator_057631eead535247b90aaf0200778acf(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & instance, char  param_in_0, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & param_out)     { instance.operator+=(param_in_0) = param_out; }
    void method_decorator_d30aa1d815c154a8bbc756a58ab57e55(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & instance, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const & param_in_0, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & param_out)     { instance.append(param_in_0) = param_out; }
    void method_decorator_33cadff9793f5ea2a1510801c515e100(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & instance, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const & param_in_0, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_1, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_2, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & param_out)     { instance.append(param_in_0, param_in_1, param_in_2) = param_out; }
    void method_decorator_83e3b61a389256d7abaafd84bb810a15(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & instance, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_0, char  param_in_1, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & param_out)     { instance.append(param_in_0, param_in_1) = param_out; }
    void method_decorator_725d0a5f64025239b39acb6b7d35a5ee(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & instance, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const & param_in_0, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & param_out)     { instance.assign(param_in_0) = param_out; }
    void method_decorator_08e4496b4a835162910792efb5feaf17(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & instance, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const & param_in_0, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_1, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_2, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & param_out)     { instance.assign(param_in_0, param_in_1, param_in_2) = param_out; }
    void method_decorator_f7186bbf0f325105a1760cbe9ff3e10a(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & instance, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_0, char  param_in_1, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & param_out)     { instance.assign(param_in_0, param_in_1) = param_out; }
    void method_decorator_71c42988389450368465691bcd9320c8(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & instance, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_0, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const & param_in_1, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & param_out)     { instance.insert(param_in_0, param_in_1) = param_out; }
    void method_decorator_7c083b13944c55789686a72d2ed0c4e0(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & instance, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_0, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const & param_in_1, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_2, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_3, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & param_out)     { instance.insert(param_in_0, param_in_1, param_in_2, param_in_3) = param_out; }
    void method_decorator_a41a53f4fb9856fbbb8b2ff63ae51907(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & instance, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_0, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_1, char  param_in_2, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & param_out)     { instance.insert(param_in_0, param_in_1, param_in_2) = param_out; }
    void method_decorator_82886daa023b5094b01e8f20ba6f1255(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & instance, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_0, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_1, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & param_out)     { instance.erase(param_in_0, param_in_1) = param_out; }
    void method_decorator_cd19f69563a6507eada682394eb4cc09(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & instance, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_0, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_1, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const & param_in_2, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & param_out)     { instance.replace(param_in_0, param_in_1, param_in_2) = param_out; }
    void method_decorator_d79babe2f6b5551b9c1f4b45a60fa615(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & instance, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_0, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_1, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const & param_in_2, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_3, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_4, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & param_out)     { instance.replace(param_in_0, param_in_1, param_in_2, param_in_3, param_in_4) = param_out; }
    void method_decorator_c594a873809f5a809823c79d37413371(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & instance, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_0, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_1, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_2, char  param_in_3, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & param_out)     { instance.replace(param_in_0, param_in_1, param_in_2, param_in_3) = param_out; }
}

#if defined(_MSC_VER)
    #if (_MSC_VER == 1900)
namespace boost
{
    template <> class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const volatile * get_pointer<class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const volatile >(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const volatile *c) { return c; }
}
    #endif
#endif



void wrapper_448c20257e485acda59dc59305fceb58()
{

    std::string name_a5e4e9231d6351ccb0e06756b389f0af = boost::python::extract< std::string >(boost::python::scope().attr("__name__") + ".std");
    boost::python::object module_a5e4e9231d6351ccb0e06756b389f0af(boost::python::handle<  >(boost::python::borrowed(PyImport_AddModule(name_a5e4e9231d6351ccb0e06756b389f0af.c_str()))));
    boost::python::scope().attr("std") = module_a5e4e9231d6351ccb0e06756b389f0af;
    boost::python::scope scope_a5e4e9231d6351ccb0e06756b389f0af = module_a5e4e9231d6351ccb0e06756b389f0af;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_e889957d6e2a553b820024ee62954302)() const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_20add8048fc45afb9ffc6e5302ee7354)() const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::length;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_2071b4fa22bc5919a32df9333c981030)() const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::max_size;
    void  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_5cb01221cf545dfab862caaf79a9a571)(::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , char ) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::resize;
    void  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_caf2aed523e35ef8943f5fc961c154b5)(::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::resize;
    void  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_1f9ca4f0333952fe817add3d54787a01)() = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::shrink_to_fit;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_323f12178c935e3dbc7ef328b314f365)() const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::capacity;
    void  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_abd4f6e83fd45a3384680e5862e06745)(::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::reserve;
    void  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_31ca5ad51bbe51b2885f628d587b304a)() = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::clear;
    bool  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_b271edef06005c1da54c171beb54184b)() const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::empty;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::const_reference  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_3cbd356001115f429a0976ef760ff126)(::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::operator[];
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::reference  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_5c2439bfc6cc537ab09bd5c61e98ccac)(::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::operator[];
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::const_reference  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_c7932ab8a0185852942348934c9287ce)(::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::at;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::reference  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_2b1847ed6305532081540fcee3a3039e)(::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::at;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::reference  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_492d67ed747f57fa96bdcfb12ff2b092)() = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::front;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::const_reference  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_94326a2a20fa5edcbbc03d12a4461dfa)() const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::front;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::reference  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_eaac392eb32d523c9067d99099468947)() = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::back;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::const_reference  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_2809303f869559e494a8a4bea3eba51c)() const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::back;
    class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_a41aa0fc6fb85a67b1ff7065e002ce8a)(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const &) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::operator+=;
    class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_057631eead535247b90aaf0200778acf)(char ) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::operator+=;
    class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_d30aa1d815c154a8bbc756a58ab57e55)(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const &) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::append;
    class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_33cadff9793f5ea2a1510801c515e100)(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const &, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::append;
    class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_83e3b61a389256d7abaafd84bb810a15)(::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , char ) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::append;
    void  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_8e92e189521a506894a0ef75f7f6fe73)(char ) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::push_back;
    class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_725d0a5f64025239b39acb6b7d35a5ee)(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const &) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::assign;
    class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_08e4496b4a835162910792efb5feaf17)(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const &, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::assign;
    class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_f7186bbf0f325105a1760cbe9ff3e10a)(::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , char ) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::assign;
    class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_71c42988389450368465691bcd9320c8)(::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const &) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::insert;
    class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_7c083b13944c55789686a72d2ed0c4e0)(::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const &, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::insert;
    class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_a41a53f4fb9856fbbb8b2ff63ae51907)(::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , char ) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::insert;
    class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_82886daa023b5094b01e8f20ba6f1255)(::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::erase;
    void  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_6cc18bd36b0b589e85ea783a9f39dda0)() = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::pop_back;
    class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_cd19f69563a6507eada682394eb4cc09)(::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const &) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::replace;
    class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_d79babe2f6b5551b9c1f4b45a60fa615)(::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const &, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::replace;
    class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_c594a873809f5a809823c79d37413371)(::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , char ) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::replace;
    void  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_230dd5b4274f5e5fa96515ff97f6668a)(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > &) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::swap;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_d641dcea4a665af09015a695dd75def3)(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const &, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::find;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_6f19286b7387516f9fc9357b07056c84)(char , ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::find;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_f3a1f660e3b950e8a766cdc4656109ff)(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const &, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::rfind;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_bbf7752b64fa5b40a3c09aea0f42766c)(char , ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::rfind;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_6b5ac38efbe256d0adb8d10f9146ce09)(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const &, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::find_first_of;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_f2d293ee3e415ddb96450dcaf6694d99)(char , ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::find_first_of;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_b68be96f2e1358128661859b0e67d858)(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const &, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::find_last_of;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_851c10c3850654cf967ac41c56e03da4)(char , ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::find_last_of;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_57b5191401635fd196617e2e6046b28e)(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const &, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::find_first_not_of;
//    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_88879920cd74551c9cc2184263fbe18d)(char , ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::find_first_not_of;
//    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_0e10a3100cc4580294370110e0d3d099)(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const &, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::_last_not_of;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_00d7f7a52f90511581fafe208f4dcb60)(char , ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::find_last_not_of;
    boost::python::class_< class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >, autowig::Held< class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > >::Type > class_448c20257e485acda59dc59305fceb58("_BasicString_448c20257e485acda59dc59305fceb58", "", boost::python::no_init);
    class_448c20257e485acda59dc59305fceb58.def(boost::python::init<  >(""));
//    class_448c20257e485acda59dc59305fceb58.def(boost::python::init< class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const & >(""));
//    class_448c20257e485acda59dc59305fceb58.def(boost::python::init< class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const &, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  >(""));
//    class_448c20257e485acda59dc59305fceb58.def("__len__", method_pointer_e889957d6e2a553b820024ee62954302, "");
//    class_448c20257e485acda59dc59305fceb58.def("length", method_pointer_20add8048fc45afb9ffc6e5302ee7354, "");
/*    class_448c20257e485acda59dc59305fceb58.def("max_size", method_pointer_2071b4fa22bc5919a32df9333c981030, "");
    class_448c20257e485acda59dc59305fceb58.def("resize", method_pointer_5cb01221cf545dfab862caaf79a9a571, "");
    class_448c20257e485acda59dc59305fceb58.def("resize", method_pointer_caf2aed523e35ef8943f5fc961c154b5, "");
    class_448c20257e485acda59dc59305fceb58.def("shrink_to_fit", method_pointer_1f9ca4f0333952fe817add3d54787a01, "");
    class_448c20257e485acda59dc59305fceb58.def("capacity", method_pointer_323f12178c935e3dbc7ef328b314f365, "");
    class_448c20257e485acda59dc59305fceb58.def("reserve", method_pointer_abd4f6e83fd45a3384680e5862e06745, "");
*/
//    class_448c20257e485acda59dc59305fceb58.def("clear", method_pointer_31ca5ad51bbe51b2885f628d587b304a, "");
//    class_448c20257e485acda59dc59305fceb58.def("empty", method_pointer_b271edef06005c1da54c171beb54184b, "");
/*    class_448c20257e485acda59dc59305fceb58.def("__getitem__", method_pointer_3cbd356001115f429a0976ef760ff126, boost::python::return_value_policy< boost::python::return_by_value >(), "");
    class_448c20257e485acda59dc59305fceb58.def("__getitem__", method_pointer_5c2439bfc6cc537ab09bd5c61e98ccac, boost::python::return_value_policy< boost::python::return_by_value >(), "");
    class_448c20257e485acda59dc59305fceb58.def("__getitem__", autowig::method_decorator_5c2439bfc6cc537ab09bd5c61e98ccac);
*/    class_448c20257e485acda59dc59305fceb58.def("at", method_pointer_c7932ab8a0185852942348934c9287ce, boost::python::return_value_policy< boost::python::return_by_value >(), "");
    class_448c20257e485acda59dc59305fceb58.def("at", method_pointer_2b1847ed6305532081540fcee3a3039e, boost::python::return_value_policy< boost::python::return_by_value >(), "");
    class_448c20257e485acda59dc59305fceb58.def("at", autowig::method_decorator_2b1847ed6305532081540fcee3a3039e);
/*    class_448c20257e485acda59dc59305fceb58.def("__iadd__", method_pointer_a41aa0fc6fb85a67b1ff7065e002ce8a, boost::python::return_internal_reference<>(), "");
    class_448c20257e485acda59dc59305fceb58.def("__iadd__", autowig::method_decorator_a41aa0fc6fb85a67b1ff7065e002ce8a);
    class_448c20257e485acda59dc59305fceb58.def("__iadd__", method_pointer_057631eead535247b90aaf0200778acf, boost::python::return_internal_reference<>(), "");
    class_448c20257e485acda59dc59305fceb58.def("__iadd__", autowig::method_decorator_057631eead535247b90aaf0200778acf);
    class_448c20257e485acda59dc59305fceb58.def("append", method_pointer_d30aa1d815c154a8bbc756a58ab57e55, boost::python::return_internal_reference<>(), "");
    class_448c20257e485acda59dc59305fceb58.def("append", autowig::method_decorator_d30aa1d815c154a8bbc756a58ab57e55);
    class_448c20257e485acda59dc59305fceb58.def("append", method_pointer_33cadff9793f5ea2a1510801c515e100, boost::python::return_internal_reference<>(), "");
    class_448c20257e485acda59dc59305fceb58.def("append", autowig::method_decorator_33cadff9793f5ea2a1510801c515e100);
    class_448c20257e485acda59dc59305fceb58.def("append", method_pointer_83e3b61a389256d7abaafd84bb810a15, boost::python::return_internal_reference<>(), "");
    class_448c20257e485acda59dc59305fceb58.def("append", autowig::method_decorator_83e3b61a389256d7abaafd84bb810a15);
*/    class_448c20257e485acda59dc59305fceb58.def("push_back", method_pointer_8e92e189521a506894a0ef75f7f6fe73, "");
/*    class_448c20257e485acda59dc59305fceb58.def("assign", method_pointer_725d0a5f64025239b39acb6b7d35a5ee, boost::python::return_internal_reference<>(), "");
    class_448c20257e485acda59dc59305fceb58.def("assign", autowig::method_decorator_725d0a5f64025239b39acb6b7d35a5ee);
    class_448c20257e485acda59dc59305fceb58.def("assign", method_pointer_08e4496b4a835162910792efb5feaf17, boost::python::return_internal_reference<>(), "");
    class_448c20257e485acda59dc59305fceb58.def("assign", autowig::method_decorator_08e4496b4a835162910792efb5feaf17);
    class_448c20257e485acda59dc59305fceb58.def("assign", method_pointer_f7186bbf0f325105a1760cbe9ff3e10a, boost::python::return_internal_reference<>(), "");
    class_448c20257e485acda59dc59305fceb58.def("assign", autowig::method_decorator_f7186bbf0f325105a1760cbe9ff3e10a);
    class_448c20257e485acda59dc59305fceb58.def("insert", method_pointer_71c42988389450368465691bcd9320c8, boost::python::return_internal_reference<>(), "");
    class_448c20257e485acda59dc59305fceb58.def("insert", autowig::method_decorator_71c42988389450368465691bcd9320c8);
    class_448c20257e485acda59dc59305fceb58.def("insert", method_pointer_7c083b13944c55789686a72d2ed0c4e0, boost::python::return_internal_reference<>(), "");
    class_448c20257e485acda59dc59305fceb58.def("insert", autowig::method_decorator_7c083b13944c55789686a72d2ed0c4e0);
    class_448c20257e485acda59dc59305fceb58.def("insert", method_pointer_a41a53f4fb9856fbbb8b2ff63ae51907, boost::python::return_internal_reference<>(), "");
    class_448c20257e485acda59dc59305fceb58.def("insert", autowig::method_decorator_a41a53f4fb9856fbbb8b2ff63ae51907);
*/    class_448c20257e485acda59dc59305fceb58.def("erase", method_pointer_82886daa023b5094b01e8f20ba6f1255, boost::python::return_internal_reference<>(), "");
    class_448c20257e485acda59dc59305fceb58.def("erase", autowig::method_decorator_82886daa023b5094b01e8f20ba6f1255);
//    class_448c20257e485acda59dc59305fceb58.def("pop_back", method_pointer_6cc18bd36b0b589e85ea783a9f39dda0, "");
/*    class_448c20257e485acda59dc59305fceb58.def("replace", method_pointer_cd19f69563a6507eada682394eb4cc09, boost::python::return_internal_reference<>(), "");
    class_448c20257e485acda59dc59305fceb58.def("replace", autowig::method_decorator_cd19f69563a6507eada682394eb4cc09);
    class_448c20257e485acda59dc59305fceb58.def("replace", method_pointer_d79babe2f6b5551b9c1f4b45a60fa615, boost::python::return_internal_reference<>(), "");
    class_448c20257e485acda59dc59305fceb58.def("replace", autowig::method_decorator_d79babe2f6b5551b9c1f4b45a60fa615);
    class_448c20257e485acda59dc59305fceb58.def("replace", method_pointer_c594a873809f5a809823c79d37413371, boost::python::return_internal_reference<>(), "");
    class_448c20257e485acda59dc59305fceb58.def("replace", autowig::method_decorator_c594a873809f5a809823c79d37413371);
*///    class_448c20257e485acda59dc59305fceb58.def("swap", method_pointer_230dd5b4274f5e5fa96515ff97f6668a, "");
/*    class_448c20257e485acda59dc59305fceb58.def("find", method_pointer_d641dcea4a665af09015a695dd75def3, "");
    class_448c20257e485acda59dc59305fceb58.def("find", method_pointer_6f19286b7387516f9fc9357b07056c84, "");
    class_448c20257e485acda59dc59305fceb58.def("rfind", method_pointer_f3a1f660e3b950e8a766cdc4656109ff, "");
    class_448c20257e485acda59dc59305fceb58.def("rfind", method_pointer_bbf7752b64fa5b40a3c09aea0f42766c, "");
    class_448c20257e485acda59dc59305fceb58.def("find_first_of", method_pointer_6b5ac38efbe256d0adb8d10f9146ce09, "");
    class_448c20257e485acda59dc59305fceb58.def("find_first_of", method_pointer_f2d293ee3e415ddb96450dcaf6694d99, "");
    class_448c20257e485acda59dc59305fceb58.def("find_last_of", method_pointer_b68be96f2e1358128661859b0e67d858, "");
    class_448c20257e485acda59dc59305fceb58.def("find_last_of", method_pointer_851c10c3850654cf967ac41c56e03da4, "");
*///    class_448c20257e485acda59dc59305fceb58.def("find_first_not_of", method_pointer_57b5191401635fd196617e2e6046b28e, "");
//    class_448c20257e485acda59dc59305fceb58.def("find_first_not_of", method_pointer_88879920cd74551c9cc2184263fbe18d, "");
//    class_448c20257e485acda59dc59305fceb58.def("find_last_not_of", method_pointer_0e10a3100cc4580294370110e0d3d099, "");
//    class_448c20257e485acda59dc59305fceb58.def("find_last_not_of", method_pointer_00d7f7a52f90511581fafe208f4dcb60, "");
    class_448c20257e485acda59dc59305fceb58.def_readonly("npos", ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::npos, "");

}