#include "_stat_tool.h"



namespace autowig
{

    void method_decorator_daccc86b6eb856fca01e1bd13c4a5118(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & instance, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const & param_in_0, const class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & param_out) { instance.operator+=(param_in_0) = param_out; }
    void method_decorator_1c47649782955d76bd7cb3b9a8b29f15(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & instance, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::value_type  param_in_0, const class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & param_out) { instance.operator+=(param_in_0) = param_out; }
    void method_decorator_78b256da391d583eb486b27817505930(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & instance, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const & param_in_0, const class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & param_out) { instance.append(param_in_0) = param_out; }
    void method_decorator_e5fbdd570bbb5bfaadf3d281c2848c7f(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & instance, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const & param_in_0, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_1, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_2, const class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & param_out) { instance.append(param_in_0, param_in_1, param_in_2) = param_out; }
    void method_decorator_59e62862c2185362b45c5cdbb6da6d4a(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & instance, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_0, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::value_type  param_in_1, const class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & param_out) { instance.append(param_in_0, param_in_1) = param_out; }
    void method_decorator_8b7872920f625407b8a2cfb6452f4920(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & instance, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const & param_in_0, const class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & param_out) { instance.assign(param_in_0) = param_out; }
    void method_decorator_cde2cef0c9545531ad04589bd3e3f5b3(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & instance, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const & param_in_0, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_1, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_2, const class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & param_out) { instance.assign(param_in_0, param_in_1, param_in_2) = param_out; }
    void method_decorator_5e9418d245065b589fdadd8809032bf4(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & instance, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_0, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::value_type  param_in_1, const class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & param_out) { instance.assign(param_in_0, param_in_1) = param_out; }
    void method_decorator_6a4b6ed7e786548eab62a16e6499e965(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & instance, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_0, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const & param_in_1, const class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & param_out) { instance.insert(param_in_0, param_in_1) = param_out; }
    void method_decorator_9d105c1751735236a9449286b64c21f7(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & instance, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_0, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const & param_in_1, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_2, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_3, const class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & param_out) { instance.insert(param_in_0, param_in_1, param_in_2, param_in_3) = param_out; }
    void method_decorator_0b846e4a20985dd6becca36613d9b06e(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & instance, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_0, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_1, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::value_type  param_in_2, const class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & param_out) { instance.insert(param_in_0, param_in_1, param_in_2) = param_out; }
    void method_decorator_a7e76683bfa95efdbdf11261c9a6b86b(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & instance, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_0, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_1, const class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & param_out) { instance.erase(param_in_0, param_in_1) = param_out; }
    void method_decorator_814a0ee0211451ee9608fb89ce171c01(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & instance, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_0, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_1, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const & param_in_2, const class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & param_out) { instance.replace(param_in_0, param_in_1, param_in_2) = param_out; }
    void method_decorator_6d0a8ebb5e665d16a2a7596574e22c8a(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & instance, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_0, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_1, class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const & param_in_2, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_3, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_4, const class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & param_out) { instance.replace(param_in_0, param_in_1, param_in_2, param_in_3, param_in_4) = param_out; }
    void method_decorator_f0de365241e65d5383172c1233c8d70f(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & instance, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_0, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_1, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  param_in_2, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::value_type  param_in_3, const class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & param_out) { instance.replace(param_in_0, param_in_1, param_in_2, param_in_3) = param_out; }
}

#if defined(_MSC_VER)
    #if (_MSC_VER == 1900)
namespace boost
{
    template <> class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const volatile * get_pointer<class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const volatile >(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const volatile *c) { return c; }
}
    #endif
#endif



void wrapper_448c20257e485acda59dc59305fceb58()
{

    std::string name_a5e4e9231d6351ccb0e06756b389f0af = boost::python::extract< std::string >(boost::python::scope().attr("__name__") + ".std");
    boost::python::object module_a5e4e9231d6351ccb0e06756b389f0af(boost::python::handle<  >(boost::python::borrowed(PyImport_AddModule(name_a5e4e9231d6351ccb0e06756b389f0af.c_str()))));
    boost::python::scope().attr("std") = module_a5e4e9231d6351ccb0e06756b389f0af;
    boost::python::scope scope_a5e4e9231d6351ccb0e06756b389f0af = module_a5e4e9231d6351ccb0e06756b389f0af;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_2145f907d7315014b56a3d38d94b987e)() const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_df9831bb73e05fd3886a69a4ec5322b3)() const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::length;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_e21688d111845ac386dc11f07efa29e0)() const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::max_size;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_d61a5f3b84555636bd548de837510951)() const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::capacity;
    void  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_7bc8a070995958abbd96617bc13868bf)(::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::value_type ) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::resize;
    void  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_97c6b03b3d8151a8b66363bd75c9b1f8)(::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::resize;
    void  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_fb666fb0a91651dda7ba7e458e7537dd)(::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::reserve;
    void  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_4a5c9941f91159a0aa3512a4dc9a21c0)() = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::shrink_to_fit;
    void  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_18338d7d7a06576da8abf13286b250a2)() = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::clear;
    bool  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_5644efafbcec5aa294df50c490bc5395)() const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::empty;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::const_reference  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_a1d2e648dcf953baa018b952b6dcb375)(::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::operator[];
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::const_reference  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_b10f57ef3e935b7ea64929054a981b74)(::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::at;
    class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_daccc86b6eb856fca01e1bd13c4a5118)(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const &) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::operator+=;
    class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_1c47649782955d76bd7cb3b9a8b29f15)(::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::value_type ) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::operator+=;
    class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_78b256da391d583eb486b27817505930)(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const &) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::append;
    class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_e5fbdd570bbb5bfaadf3d281c2848c7f)(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const &, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::append;
    class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_59e62862c2185362b45c5cdbb6da6d4a)(::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::value_type ) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::append;
    void  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_bef57a1856415398a879a1abfaf3f556)(::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::value_type ) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::push_back;
    void  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_2d3ea5e214f559fa8c6d7c0ef593c0bc)() = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::pop_back;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::const_reference  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_6e9762b80f2d517dbbb0d5c21672c2c3)() const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::front;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::const_reference  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_d859210139c255d1bf60a43276df9d65)() const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::back;
    class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_8b7872920f625407b8a2cfb6452f4920)(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const &) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::assign;
    class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_cde2cef0c9545531ad04589bd3e3f5b3)(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const &, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::assign;
    class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_5e9418d245065b589fdadd8809032bf4)(::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::value_type ) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::assign;
    class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_6a4b6ed7e786548eab62a16e6499e965)(::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const &) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::insert;
    class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_9d105c1751735236a9449286b64c21f7)(::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const &, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::insert;
    class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_0b846e4a20985dd6becca36613d9b06e)(::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::value_type ) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::insert;
    class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_a7e76683bfa95efdbdf11261c9a6b86b)(::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::erase;
    class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_814a0ee0211451ee9608fb89ce171c01)(::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const &) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::replace;
    class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_6d0a8ebb5e665d16a2a7596574e22c8a)(::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const &, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::replace;
    class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > & (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_f0de365241e65d5383172c1233c8d70f)(::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type , ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::value_type ) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::replace;
    void  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_aa8b42541e05528c84df4e255d83c09c)(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > &) = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::swap;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_d0d0cd0dfd125ff1a71fb76fc231f0c3)(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const &, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::find;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_6a40112811d257b2be9f8538d39a53fd)(::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::value_type , ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::find;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_760655f5c25e5181b8f805b56acfa894)(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const &, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::rfind;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_51835c57a6f35a01b040c66ccbac99b9)(::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::value_type , ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::rfind;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_1970c8f5f3b9553a8b0cf8d5d316a0d7)(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const &, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::find_first_of;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_c868367ec1e651f08c6b9a2661cf99c4)(::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::value_type , ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::find_first_of;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_e41bf664868f5b66b545e990ad314384)(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const &, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::find_last_of;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_b257dfa6ea61547786ea191a79d52bcd)(::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::value_type , ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::find_last_of;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_ea60efdc2a97548791ee16872dee36b6)(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const &, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::find_first_not_of;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_9847fca1558c57e2a75ec28f29baaf54)(::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::value_type , ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::find_first_not_of;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_1dfc9f3aa06d543e8c85998d0c1f55f4)(class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > const &, ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::find_last_not_of;
    ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_b53ff808ae525448b66544da8b49a13f)(::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::value_type , ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::size_type ) const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::find_last_not_of;
    bool  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_812dc6f169f559c999eaf6257ca550d3)() const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::__invariants;
    bool  (::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >::*method_pointer_2385f24cd2e954a4aa2e37c867c60948)() const = &::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::__is_long;
    boost::python::class_< class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >, autowig::Held< class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > >::Type > class_448c20257e485acda59dc59305fceb58("_BasicString_448c20257e485acda59dc59305fceb58", "", boost::python::no_init);
    class_448c20257e485acda59dc59305fceb58.def("__len__", method_pointer_2145f907d7315014b56a3d38d94b987e, "");
    class_448c20257e485acda59dc59305fceb58.def("length", method_pointer_df9831bb73e05fd3886a69a4ec5322b3, "");
    class_448c20257e485acda59dc59305fceb58.def("max_size", method_pointer_e21688d111845ac386dc11f07efa29e0, "");
    class_448c20257e485acda59dc59305fceb58.def("capacity", method_pointer_d61a5f3b84555636bd548de837510951, "");
    class_448c20257e485acda59dc59305fceb58.def("resize", method_pointer_7bc8a070995958abbd96617bc13868bf, "");
    class_448c20257e485acda59dc59305fceb58.def("resize", method_pointer_97c6b03b3d8151a8b66363bd75c9b1f8, "");
    class_448c20257e485acda59dc59305fceb58.def("reserve", method_pointer_fb666fb0a91651dda7ba7e458e7537dd, "");
    class_448c20257e485acda59dc59305fceb58.def("shrink_to_fit", method_pointer_4a5c9941f91159a0aa3512a4dc9a21c0, "");
    class_448c20257e485acda59dc59305fceb58.def("clear", method_pointer_18338d7d7a06576da8abf13286b250a2, "");
    class_448c20257e485acda59dc59305fceb58.def("empty", method_pointer_5644efafbcec5aa294df50c490bc5395, "");
    class_448c20257e485acda59dc59305fceb58.def("__getitem__", method_pointer_a1d2e648dcf953baa018b952b6dcb375, boost::python::return_value_policy< boost::python::return_by_value >(), "");
    class_448c20257e485acda59dc59305fceb58.def("at", method_pointer_b10f57ef3e935b7ea64929054a981b74, boost::python::return_value_policy< boost::python::return_by_value >(), "");
    class_448c20257e485acda59dc59305fceb58.def("__iadd__", method_pointer_daccc86b6eb856fca01e1bd13c4a5118, boost::python::return_internal_reference<>(), "");
    class_448c20257e485acda59dc59305fceb58.def("__iadd__", autowig::method_decorator_daccc86b6eb856fca01e1bd13c4a5118);
    class_448c20257e485acda59dc59305fceb58.def("__iadd__", method_pointer_1c47649782955d76bd7cb3b9a8b29f15, boost::python::return_internal_reference<>(), "");
    class_448c20257e485acda59dc59305fceb58.def("__iadd__", autowig::method_decorator_1c47649782955d76bd7cb3b9a8b29f15);
    class_448c20257e485acda59dc59305fceb58.def("append", method_pointer_78b256da391d583eb486b27817505930, boost::python::return_internal_reference<>(), "");
    class_448c20257e485acda59dc59305fceb58.def("append", autowig::method_decorator_78b256da391d583eb486b27817505930);
    class_448c20257e485acda59dc59305fceb58.def("append", method_pointer_e5fbdd570bbb5bfaadf3d281c2848c7f, boost::python::return_internal_reference<>(), "");
    class_448c20257e485acda59dc59305fceb58.def("append", autowig::method_decorator_e5fbdd570bbb5bfaadf3d281c2848c7f);
    class_448c20257e485acda59dc59305fceb58.def("append", method_pointer_59e62862c2185362b45c5cdbb6da6d4a, boost::python::return_internal_reference<>(), "");
    class_448c20257e485acda59dc59305fceb58.def("append", autowig::method_decorator_59e62862c2185362b45c5cdbb6da6d4a);
    class_448c20257e485acda59dc59305fceb58.def("push_back", method_pointer_bef57a1856415398a879a1abfaf3f556, "");
    class_448c20257e485acda59dc59305fceb58.def("pop_back", method_pointer_2d3ea5e214f559fa8c6d7c0ef593c0bc, "");
    class_448c20257e485acda59dc59305fceb58.def("front", method_pointer_6e9762b80f2d517dbbb0d5c21672c2c3, boost::python::return_value_policy< boost::python::return_by_value >(), "");
    class_448c20257e485acda59dc59305fceb58.def("back", method_pointer_d859210139c255d1bf60a43276df9d65, boost::python::return_value_policy< boost::python::return_by_value >(), "");
    class_448c20257e485acda59dc59305fceb58.def("assign", method_pointer_8b7872920f625407b8a2cfb6452f4920, boost::python::return_internal_reference<>(), "");
    class_448c20257e485acda59dc59305fceb58.def("assign", autowig::method_decorator_8b7872920f625407b8a2cfb6452f4920);
    class_448c20257e485acda59dc59305fceb58.def("assign", method_pointer_cde2cef0c9545531ad04589bd3e3f5b3, boost::python::return_internal_reference<>(), "");
    class_448c20257e485acda59dc59305fceb58.def("assign", autowig::method_decorator_cde2cef0c9545531ad04589bd3e3f5b3);
    class_448c20257e485acda59dc59305fceb58.def("assign", method_pointer_5e9418d245065b589fdadd8809032bf4, boost::python::return_internal_reference<>(), "");
    class_448c20257e485acda59dc59305fceb58.def("assign", autowig::method_decorator_5e9418d245065b589fdadd8809032bf4);
    class_448c20257e485acda59dc59305fceb58.def("insert", method_pointer_6a4b6ed7e786548eab62a16e6499e965, boost::python::return_internal_reference<>(), "");
    class_448c20257e485acda59dc59305fceb58.def("insert", autowig::method_decorator_6a4b6ed7e786548eab62a16e6499e965);
    class_448c20257e485acda59dc59305fceb58.def("insert", method_pointer_9d105c1751735236a9449286b64c21f7, boost::python::return_internal_reference<>(), "");
    class_448c20257e485acda59dc59305fceb58.def("insert", autowig::method_decorator_9d105c1751735236a9449286b64c21f7);
    class_448c20257e485acda59dc59305fceb58.def("insert", method_pointer_0b846e4a20985dd6becca36613d9b06e, boost::python::return_internal_reference<>(), "");
    class_448c20257e485acda59dc59305fceb58.def("insert", autowig::method_decorator_0b846e4a20985dd6becca36613d9b06e);
    class_448c20257e485acda59dc59305fceb58.def("erase", method_pointer_a7e76683bfa95efdbdf11261c9a6b86b, boost::python::return_internal_reference<>(), "");
    class_448c20257e485acda59dc59305fceb58.def("erase", autowig::method_decorator_a7e76683bfa95efdbdf11261c9a6b86b);
    class_448c20257e485acda59dc59305fceb58.def("replace", method_pointer_814a0ee0211451ee9608fb89ce171c01, boost::python::return_internal_reference<>(), "");
    class_448c20257e485acda59dc59305fceb58.def("replace", autowig::method_decorator_814a0ee0211451ee9608fb89ce171c01);
    class_448c20257e485acda59dc59305fceb58.def("replace", method_pointer_6d0a8ebb5e665d16a2a7596574e22c8a, boost::python::return_internal_reference<>(), "");
    class_448c20257e485acda59dc59305fceb58.def("replace", autowig::method_decorator_6d0a8ebb5e665d16a2a7596574e22c8a);
    class_448c20257e485acda59dc59305fceb58.def("replace", method_pointer_f0de365241e65d5383172c1233c8d70f, boost::python::return_internal_reference<>(), "");
    class_448c20257e485acda59dc59305fceb58.def("replace", autowig::method_decorator_f0de365241e65d5383172c1233c8d70f);
    class_448c20257e485acda59dc59305fceb58.def("swap", method_pointer_aa8b42541e05528c84df4e255d83c09c, "");
    class_448c20257e485acda59dc59305fceb58.def("find", method_pointer_d0d0cd0dfd125ff1a71fb76fc231f0c3, "");
    class_448c20257e485acda59dc59305fceb58.def("find", method_pointer_6a40112811d257b2be9f8538d39a53fd, "");
    class_448c20257e485acda59dc59305fceb58.def("rfind", method_pointer_760655f5c25e5181b8f805b56acfa894, "");
    class_448c20257e485acda59dc59305fceb58.def("rfind", method_pointer_51835c57a6f35a01b040c66ccbac99b9, "");
    class_448c20257e485acda59dc59305fceb58.def("find_first_of", method_pointer_1970c8f5f3b9553a8b0cf8d5d316a0d7, "");
    class_448c20257e485acda59dc59305fceb58.def("find_first_of", method_pointer_c868367ec1e651f08c6b9a2661cf99c4, "");
    class_448c20257e485acda59dc59305fceb58.def("find_last_of", method_pointer_e41bf664868f5b66b545e990ad314384, "");
    class_448c20257e485acda59dc59305fceb58.def("find_last_of", method_pointer_b257dfa6ea61547786ea191a79d52bcd, "");
    class_448c20257e485acda59dc59305fceb58.def("find_first_not_of", method_pointer_ea60efdc2a97548791ee16872dee36b6, "");
    class_448c20257e485acda59dc59305fceb58.def("find_first_not_of", method_pointer_9847fca1558c57e2a75ec28f29baaf54, "");
    class_448c20257e485acda59dc59305fceb58.def("find_last_not_of", method_pointer_1dfc9f3aa06d543e8c85998d0c1f55f4, "");
    class_448c20257e485acda59dc59305fceb58.def("find_last_not_of", method_pointer_b53ff808ae525448b66544da8b49a13f, "");
    class_448c20257e485acda59dc59305fceb58.def("invariants", method_pointer_812dc6f169f559c999eaf6257ca550d3, "");
    class_448c20257e485acda59dc59305fceb58.def("is_long", method_pointer_2385f24cd2e954a4aa2e37c867c60948, "");
    class_448c20257e485acda59dc59305fceb58.def_readonly("npos", ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >::npos, "");

}