# -*-python-*-

import os
bn = os.path.basename

Import( "env" )

lib_env = env.Copy()


# Import/Export symbols for windows
if lib_env['compiler'] == 'mingw':
    LINKFLAGS=["-enable-stdcall-fixup",
               "-enable-auto-import",
               "-enable-runtime-pseudo-reloc",
               "-s"]
    lib_env.AppendUnique(LINKFLAGS=LINKFLAGS)

includes= lib_env.ALEAGlob('*.h')
sources = lib_env.ALEAGlob('*.cpp')

# Add hpp files
hpp = Split("""
reestimation.cpp
chain_reestimation.cpp
""")

includes += hpp
sources = [x for x in sources if bn(x) not in hpp]


# Add defines to export symbols on Windows
lib_env.AppendUnique(CPPDEFINES=['MESSAGE'])
lib_env.AppendUnique(LIBS=['vptool'])

inc = lib_env.ALEAIncludes( "stat_tool", includes )

lib = lib_env.ALEALibrary( "vpstat_tool", 
                           sources, 
                           )
