# -*-python-*-

import os
bn = os.path.basename

Import( "env" )

lib_env = env.Clone()

lib_env.EnableQt4Modules(['QtCore','QtOpenGL', 'QtGui'])

# Import/Export symbols for windows
if lib_env['compiler'] == 'mingw':
    LINKFLAGS=["-enable-stdcall-fixup",
               "-enable-auto-import",
               "-enable-runtime-pseudo-reloc",
               "-s"]
    lib_env.AppendUnique(LINKFLAGS=LINKFLAGS)

includes= lib_env.ALEAGlob('*.h')
includes += lib_env.ALEAGlob('*.hpp')
sources = lib_env.ALEAGlob('*.cpp')


# Add defines to export symbols on Windows
#if env['message']:
#    lib_env.AppendUnique(CPPDEFINES=['MESSAGE'])

lib_env.AppendUnique(LIBS=['vptool'])

my_debug = False

if env['debug']:
    lib_env.Append(CPPDEFINES= ['DEBUG'])

if my_debug:   
    lib_env.AppendUnique(LIBS=['efence'])
    CPPFLAGS=["-g"]
    lib_env.AppendUnique(CPPFLAGS=CPPFLAGS)
    if '-DNDEBUG' in lib_env._dict['CCFLAGS']:
        lib_env._dict['CCFLAGS'] = []
    if '-DNDEBUG' in lib_env._dict['CXXFLAGS']:
        lib_env._dict['CXXFLAGS'] = []
        

inc = lib_env.ALEAIncludes( "stat_tool", includes )
lib = lib_env.ALEALibrary( "vpstat_tool", sources )

