# -*-python-*-

from openalea.sconsx import config, environ
import os

pj = os.path.join
ALEASolution = config.ALEASolution
name = 'tree'

options = Variables(['../options.py', 'options.py'], ARGUMENTS)
tools = ['install']

env = ALEASolution(options, tools)

# Set build directory
prefix = env['build_prefix']

# Build stage
SConscript(pj(prefix,"src/cpp/SConscript"), exports="env")

Default("build")
